package org.mskcc.cbio.clinicaldata.darwin.dao.dvcbio;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.DmtClinicalBrainSpine;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.DmtClinicalBrainSpineExample;


import java.util.List;

public interface DmtClinicalBrainSpineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int countByExample(DmtClinicalBrainSpineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int deleteByExample(DmtClinicalBrainSpineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insert(DmtClinicalBrainSpine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insertSelective(DmtClinicalBrainSpine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<DmtClinicalBrainSpine> selectByExample(DmtClinicalBrainSpineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") DmtClinicalBrainSpine record, @Param("example") DmtClinicalBrainSpineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExample(@Param("record") DmtClinicalBrainSpine record, @Param("example") DmtClinicalBrainSpineExample example);
}