package org.mskcc.cbio.clinicaldata.darwin.dao.dvcbio;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientAppointment;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientAppointmentExample;


import java.util.List;

public interface PatientAppointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.APPOINTMENTS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int countByExample(PatientAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.APPOINTMENTS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int deleteByExample(PatientAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.APPOINTMENTS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insert(PatientAppointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.APPOINTMENTS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insertSelective(PatientAppointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.APPOINTMENTS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<PatientAppointment> selectByExample(PatientAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.APPOINTMENTS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") PatientAppointment record, @Param("example") PatientAppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.APPOINTMENTS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExample(@Param("record") PatientAppointment record, @Param("example") PatientAppointmentExample example);
}