package org.mskcc.cbio.clinicaldata.darwin.dao.dvcbio;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientMedOrder;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientMedOrderExample;


import java.util.List;

public interface PatientMedOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int countByExample(PatientMedOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int deleteByExample(PatientMedOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insert(PatientMedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insertSelective(PatientMedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<PatientMedOrder> selectByExample(PatientMedOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") PatientMedOrder record, @Param("example") PatientMedOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExample(@Param("record") PatientMedOrder record, @Param("example") PatientMedOrderExample example);
}