package org.mskcc.cbio.clinicaldata.darwin.dao.dvcbio;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientMedOrder2;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientMedOrder2Example;


import java.util.List;

public interface PatientMedOrder2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int countByExample(PatientMedOrder2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int deleteByExample(PatientMedOrder2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insert(PatientMedOrder2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insertSelective(PatientMedOrder2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<PatientMedOrder2> selectByExample(PatientMedOrder2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") PatientMedOrder2 record, @Param("example") PatientMedOrder2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExample(@Param("record") PatientMedOrder2 record, @Param("example") PatientMedOrder2Example example);
}