package org.mskcc.cbio.clinicaldata.darwin.dao.dvcbio;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientInpatientRecord;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientInpatientRecordExample;


import java.util.List;

public interface PatientInpatientRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.INPATIENT_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int countByExample(PatientInpatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.INPATIENT_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int deleteByExample(PatientInpatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.INPATIENT_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insert(PatientInpatientRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.INPATIENT_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insertSelective(PatientInpatientRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.INPATIENT_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<PatientInpatientRecord> selectByExample(PatientInpatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.INPATIENT_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") PatientInpatientRecord record, @Param("example") PatientInpatientRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.INPATIENT_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExample(@Param("record") PatientInpatientRecord record, @Param("example") PatientInpatientRecordExample example);
}