package org.mskcc.cbio.clinicaldata.darwin.dao.dvcbio;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientDemographics;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientDemographicsExample;


import java.util.List;

public interface PatientDemographicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DEMOGRAPHICS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int countByExample(PatientDemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DEMOGRAPHICS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int deleteByExample(PatientDemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DEMOGRAPHICS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insert(PatientDemographics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DEMOGRAPHICS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insertSelective(PatientDemographics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DEMOGRAPHICS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<PatientDemographics> selectByExample(PatientDemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DEMOGRAPHICS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") PatientDemographics record, @Param("example") PatientDemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DEMOGRAPHICS_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExample(@Param("record") PatientDemographics record, @Param("example") PatientDemographicsExample example);
}