package org.mskcc.cbio.clinicaldata.darwin.dao.dvcbio;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientClinicalNote;
import org.mskcc.cbio.clinicaldata.darwin.model.dvcbio.PatientClinicalNoteExample;


import java.util.List;

public interface PatientClinicalNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int countByExample(PatientClinicalNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int deleteByExample(PatientClinicalNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insert(PatientClinicalNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int insertSelective(PatientClinicalNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<PatientClinicalNote> selectByExampleWithBLOBs(PatientClinicalNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    List<PatientClinicalNote> selectByExample(PatientClinicalNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") PatientClinicalNote record, @Param("example") PatientClinicalNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExampleWithBLOBs(@Param("record") PatientClinicalNote record, @Param("example") PatientClinicalNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.CLINICAL_NOTE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    int updateByExample(@Param("record") PatientClinicalNote record, @Param("example") PatientClinicalNoteExample example);
}