package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

import java.util.ArrayList;
import java.util.List;

public class DmtClinicalBrainSpineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public DmtClinicalBrainSpineExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPT_ID_BRAINSPINCLINIsNull() {
            addCriterion("PT_ID_BRAINSPINCLIN is null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINIsNotNull() {
            addCriterion("PT_ID_BRAINSPINCLIN is not null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINCLIN =", value, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINNotEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINCLIN <>", value, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINGreaterThan(Integer value) {
            addCriterion("PT_ID_BRAINSPINCLIN >", value, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINGreaterThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINCLIN >=", value, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINLessThan(Integer value) {
            addCriterion("PT_ID_BRAINSPINCLIN <", value, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINLessThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINCLIN <=", value, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINIn(List<Integer> values) {
            addCriterion("PT_ID_BRAINSPINCLIN in", values, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINNotIn(List<Integer> values) {
            addCriterion("PT_ID_BRAINSPINCLIN not in", values, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINBetween(Integer value1, Integer value2) {
            addCriterion("PT_ID_BRAINSPINCLIN between", value1, value2, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINCLINNotBetween(Integer value1, Integer value2) {
            addCriterion("PT_ID_BRAINSPINCLIN not between", value1, value2, "PT_ID_BRAINSPINCLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINIsNull() {
            addCriterion("DMP_ID_BRAINSPINECLIN is null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINIsNotNull() {
            addCriterion("DMP_ID_BRAINSPINECLIN is not null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN =", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINNotEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN <>", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINGreaterThan(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN >", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINGreaterThanOrEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN >=", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINLessThan(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN <", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINLessThanOrEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN <=", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINLike(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN like", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINNotLike(String value) {
            addCriterion("DMP_ID_BRAINSPINECLIN not like", value, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINIn(List<String> values) {
            addCriterion("DMP_ID_BRAINSPINECLIN in", values, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINNotIn(List<String> values) {
            addCriterion("DMP_ID_BRAINSPINECLIN not in", values, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINBetween(String value1, String value2) {
            addCriterion("DMP_ID_BRAINSPINECLIN between", value1, value2, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINECLINNotBetween(String value1, String value2) {
            addCriterion("DMP_ID_BRAINSPINECLIN not between", value1, value2, "DMP_ID_BRAINSPINECLIN");
            return (Criteria) this;
        }

        public Criteria andGENDERIsNull() {
            addCriterion("GENDER is null");
            return (Criteria) this;
        }

        public Criteria andGENDERIsNotNull() {
            addCriterion("GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andGENDEREqualTo(String value) {
            addCriterion("GENDER =", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERNotEqualTo(String value) {
            addCriterion("GENDER <>", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERGreaterThan(String value) {
            addCriterion("GENDER >", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER >=", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERLessThan(String value) {
            addCriterion("GENDER <", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERLessThanOrEqualTo(String value) {
            addCriterion("GENDER <=", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERLike(String value) {
            addCriterion("GENDER like", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERNotLike(String value) {
            addCriterion("GENDER not like", value, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERIn(List<String> values) {
            addCriterion("GENDER in", values, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERNotIn(List<String> values) {
            addCriterion("GENDER not in", values, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERBetween(String value1, String value2) {
            addCriterion("GENDER between", value1, value2, "GENDER");
            return (Criteria) this;
        }

        public Criteria andGENDERNotBetween(String value1, String value2) {
            addCriterion("GENDER not between", value1, value2, "GENDER");
            return (Criteria) this;
        }

        public Criteria andAGEIsNull() {
            addCriterion("AGE is null");
            return (Criteria) this;
        }

        public Criteria andAGEIsNotNull() {
            addCriterion("AGE is not null");
            return (Criteria) this;
        }

        public Criteria andAGEEqualTo(Integer value) {
            addCriterion("AGE =", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGENotEqualTo(Integer value) {
            addCriterion("AGE <>", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEGreaterThan(Integer value) {
            addCriterion("AGE >", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGE >=", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGELessThan(Integer value) {
            addCriterion("AGE <", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGELessThanOrEqualTo(Integer value) {
            addCriterion("AGE <=", value, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEIn(List<Integer> values) {
            addCriterion("AGE in", values, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGENotIn(List<Integer> values) {
            addCriterion("AGE not in", values, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGEBetween(Integer value1, Integer value2) {
            addCriterion("AGE between", value1, value2, "AGE");
            return (Criteria) this;
        }

        public Criteria andAGENotBetween(Integer value1, Integer value2) {
            addCriterion("AGE not between", value1, value2, "AGE");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSIsNull() {
            addCriterion("OS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSIsNotNull() {
            addCriterion("OS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSEqualTo(String value) {
            addCriterion("OS_STATUS =", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSNotEqualTo(String value) {
            addCriterion("OS_STATUS <>", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSGreaterThan(String value) {
            addCriterion("OS_STATUS >", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSGreaterThanOrEqualTo(String value) {
            addCriterion("OS_STATUS >=", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSLessThan(String value) {
            addCriterion("OS_STATUS <", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSLessThanOrEqualTo(String value) {
            addCriterion("OS_STATUS <=", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSLike(String value) {
            addCriterion("OS_STATUS like", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSNotLike(String value) {
            addCriterion("OS_STATUS not like", value, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSIn(List<String> values) {
            addCriterion("OS_STATUS in", values, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSNotIn(List<String> values) {
            addCriterion("OS_STATUS not in", values, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSBetween(String value1, String value2) {
            addCriterion("OS_STATUS between", value1, value2, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_STATUSNotBetween(String value1, String value2) {
            addCriterion("OS_STATUS not between", value1, value2, "OS_STATUS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSIsNull() {
            addCriterion("OS_MONTHS is null");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSIsNotNull() {
            addCriterion("OS_MONTHS is not null");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSEqualTo(Integer value) {
            addCriterion("OS_MONTHS =", value, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSNotEqualTo(Integer value) {
            addCriterion("OS_MONTHS <>", value, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSGreaterThan(Integer value) {
            addCriterion("OS_MONTHS >", value, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSGreaterThanOrEqualTo(Integer value) {
            addCriterion("OS_MONTHS >=", value, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSLessThan(Integer value) {
            addCriterion("OS_MONTHS <", value, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSLessThanOrEqualTo(Integer value) {
            addCriterion("OS_MONTHS <=", value, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSIn(List<Integer> values) {
            addCriterion("OS_MONTHS in", values, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSNotIn(List<Integer> values) {
            addCriterion("OS_MONTHS not in", values, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSBetween(Integer value1, Integer value2) {
            addCriterion("OS_MONTHS between", value1, value2, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andOS_MONTHSNotBetween(Integer value1, Integer value2) {
            addCriterion("OS_MONTHS not between", value1, value2, "OS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSIsNull() {
            addCriterion("DFS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSIsNotNull() {
            addCriterion("DFS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSEqualTo(String value) {
            addCriterion("DFS_STATUS =", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSNotEqualTo(String value) {
            addCriterion("DFS_STATUS <>", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSGreaterThan(String value) {
            addCriterion("DFS_STATUS >", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSGreaterThanOrEqualTo(String value) {
            addCriterion("DFS_STATUS >=", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSLessThan(String value) {
            addCriterion("DFS_STATUS <", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSLessThanOrEqualTo(String value) {
            addCriterion("DFS_STATUS <=", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSLike(String value) {
            addCriterion("DFS_STATUS like", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSNotLike(String value) {
            addCriterion("DFS_STATUS not like", value, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSIn(List<String> values) {
            addCriterion("DFS_STATUS in", values, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSNotIn(List<String> values) {
            addCriterion("DFS_STATUS not in", values, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSBetween(String value1, String value2) {
            addCriterion("DFS_STATUS between", value1, value2, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_STATUSNotBetween(String value1, String value2) {
            addCriterion("DFS_STATUS not between", value1, value2, "DFS_STATUS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSIsNull() {
            addCriterion("DFS_MONTHS is null");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSIsNotNull() {
            addCriterion("DFS_MONTHS is not null");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSEqualTo(String value) {
            addCriterion("DFS_MONTHS =", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSNotEqualTo(String value) {
            addCriterion("DFS_MONTHS <>", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSGreaterThan(String value) {
            addCriterion("DFS_MONTHS >", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSGreaterThanOrEqualTo(String value) {
            addCriterion("DFS_MONTHS >=", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSLessThan(String value) {
            addCriterion("DFS_MONTHS <", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSLessThanOrEqualTo(String value) {
            addCriterion("DFS_MONTHS <=", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSLike(String value) {
            addCriterion("DFS_MONTHS like", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSNotLike(String value) {
            addCriterion("DFS_MONTHS not like", value, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSIn(List<String> values) {
            addCriterion("DFS_MONTHS in", values, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSNotIn(List<String> values) {
            addCriterion("DFS_MONTHS not in", values, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSBetween(String value1, String value2) {
            addCriterion("DFS_MONTHS between", value1, value2, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andDFS_MONTHSNotBetween(String value1, String value2) {
            addCriterion("DFS_MONTHS not between", value1, value2, "DFS_MONTHS");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYIsNull() {
            addCriterion("HISTOLOGY is null");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYIsNotNull() {
            addCriterion("HISTOLOGY is not null");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYEqualTo(String value) {
            addCriterion("HISTOLOGY =", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYNotEqualTo(String value) {
            addCriterion("HISTOLOGY <>", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYGreaterThan(String value) {
            addCriterion("HISTOLOGY >", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYGreaterThanOrEqualTo(String value) {
            addCriterion("HISTOLOGY >=", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYLessThan(String value) {
            addCriterion("HISTOLOGY <", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYLessThanOrEqualTo(String value) {
            addCriterion("HISTOLOGY <=", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYLike(String value) {
            addCriterion("HISTOLOGY like", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYNotLike(String value) {
            addCriterion("HISTOLOGY not like", value, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYIn(List<String> values) {
            addCriterion("HISTOLOGY in", values, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYNotIn(List<String> values) {
            addCriterion("HISTOLOGY not in", values, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYBetween(String value1, String value2) {
            addCriterion("HISTOLOGY between", value1, value2, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andHISTOLOGYNotBetween(String value1, String value2) {
            addCriterion("HISTOLOGY not between", value1, value2, "HISTOLOGY");
            return (Criteria) this;
        }

        public Criteria andGRADEIsNull() {
            addCriterion("GRADE is null");
            return (Criteria) this;
        }

        public Criteria andGRADEIsNotNull() {
            addCriterion("GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andGRADEEqualTo(String value) {
            addCriterion("GRADE =", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADENotEqualTo(String value) {
            addCriterion("GRADE <>", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADEGreaterThan(String value) {
            addCriterion("GRADE >", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADEGreaterThanOrEqualTo(String value) {
            addCriterion("GRADE >=", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADELessThan(String value) {
            addCriterion("GRADE <", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADELessThanOrEqualTo(String value) {
            addCriterion("GRADE <=", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADELike(String value) {
            addCriterion("GRADE like", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADENotLike(String value) {
            addCriterion("GRADE not like", value, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADEIn(List<String> values) {
            addCriterion("GRADE in", values, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADENotIn(List<String> values) {
            addCriterion("GRADE not in", values, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADEBetween(String value1, String value2) {
            addCriterion("GRADE between", value1, value2, "GRADE");
            return (Criteria) this;
        }

        public Criteria andGRADENotBetween(String value1, String value2) {
            addCriterion("GRADE not between", value1, value2, "GRADE");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.DMT_CLINICAL_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}