package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

public class DmtClinicalBrainSpine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.PT_ID_BRAINSPINCLIN
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer PT_ID_BRAINSPINCLIN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DMP_ID_BRAINSPINECLIN
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String DMP_ID_BRAINSPINECLIN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GENDER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String GENDER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.AGE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer AGE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_STATUS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String OS_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_MONTHS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer OS_MONTHS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_STATUS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String DFS_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_MONTHS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String DFS_MONTHS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.HISTOLOGY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String HISTOLOGY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GRADE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String GRADE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.PT_ID_BRAINSPINCLIN
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.PT_ID_BRAINSPINCLIN
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getPT_ID_BRAINSPINCLIN() {
        return PT_ID_BRAINSPINCLIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.PT_ID_BRAINSPINCLIN
     *
     * @param PT_ID_BRAINSPINCLIN the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.PT_ID_BRAINSPINCLIN
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setPT_ID_BRAINSPINCLIN(Integer PT_ID_BRAINSPINCLIN) {
        this.PT_ID_BRAINSPINCLIN = PT_ID_BRAINSPINCLIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DMP_ID_BRAINSPINECLIN
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DMP_ID_BRAINSPINECLIN
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getDMP_ID_BRAINSPINECLIN() {
        return DMP_ID_BRAINSPINECLIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DMP_ID_BRAINSPINECLIN
     *
     * @param DMP_ID_BRAINSPINECLIN the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DMP_ID_BRAINSPINECLIN
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDMP_ID_BRAINSPINECLIN(String DMP_ID_BRAINSPINECLIN) {
        this.DMP_ID_BRAINSPINECLIN = DMP_ID_BRAINSPINECLIN == null ? null : DMP_ID_BRAINSPINECLIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GENDER
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GENDER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getGENDER() {
        return GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GENDER
     *
     * @param GENDER the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GENDER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setGENDER(String GENDER) {
        this.GENDER = GENDER == null ? null : GENDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.AGE
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.AGE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getAGE() {
        return AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.AGE
     *
     * @param AGE the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.AGE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setAGE(Integer AGE) {
        this.AGE = AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_STATUS
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_STATUS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getOS_STATUS() {
        return OS_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_STATUS
     *
     * @param OS_STATUS the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_STATUS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setOS_STATUS(String OS_STATUS) {
        this.OS_STATUS = OS_STATUS == null ? null : OS_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_MONTHS
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_MONTHS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getOS_MONTHS() {
        return OS_MONTHS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_MONTHS
     *
     * @param OS_MONTHS the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.OS_MONTHS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setOS_MONTHS(Integer OS_MONTHS) {
        this.OS_MONTHS = OS_MONTHS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_STATUS
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_STATUS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getDFS_STATUS() {
        return DFS_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_STATUS
     *
     * @param DFS_STATUS the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_STATUS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDFS_STATUS(String DFS_STATUS) {
        this.DFS_STATUS = DFS_STATUS == null ? null : DFS_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_MONTHS
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_MONTHS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getDFS_MONTHS() {
        return DFS_MONTHS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_MONTHS
     *
     * @param DFS_MONTHS the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.DFS_MONTHS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDFS_MONTHS(String DFS_MONTHS) {
        this.DFS_MONTHS = DFS_MONTHS == null ? null : DFS_MONTHS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.HISTOLOGY
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.HISTOLOGY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getHISTOLOGY() {
        return HISTOLOGY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.HISTOLOGY
     *
     * @param HISTOLOGY the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.HISTOLOGY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setHISTOLOGY(String HISTOLOGY) {
        this.HISTOLOGY = HISTOLOGY == null ? null : HISTOLOGY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GRADE
     *
     * @return the value of DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GRADE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getGRADE() {
        return GRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GRADE
     *
     * @param GRADE the value for DVCBIO.DMT_CLINICAL_BRAINSPINE_V.GRADE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setGRADE(String GRADE) {
        this.GRADE = GRADE == null ? null : GRADE.trim();
    }
}