package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

import java.util.ArrayList;
import java.util.List;

public class DmtTimelineBrainSpineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public DmtTimelineBrainSpineExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPT_ID_BRAINSPINTMLNIsNull() {
            addCriterion("PT_ID_BRAINSPINTMLN is null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNIsNotNull() {
            addCriterion("PT_ID_BRAINSPINTMLN is not null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINTMLN =", value, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNNotEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINTMLN <>", value, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNGreaterThan(Integer value) {
            addCriterion("PT_ID_BRAINSPINTMLN >", value, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNGreaterThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINTMLN >=", value, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNLessThan(Integer value) {
            addCriterion("PT_ID_BRAINSPINTMLN <", value, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNLessThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_BRAINSPINTMLN <=", value, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNIn(List<Integer> values) {
            addCriterion("PT_ID_BRAINSPINTMLN in", values, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNNotIn(List<Integer> values) {
            addCriterion("PT_ID_BRAINSPINTMLN not in", values, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNBetween(Integer value1, Integer value2) {
            addCriterion("PT_ID_BRAINSPINTMLN between", value1, value2, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andPT_ID_BRAINSPINTMLNNotBetween(Integer value1, Integer value2) {
            addCriterion("PT_ID_BRAINSPINTMLN not between", value1, value2, "PT_ID_BRAINSPINTMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNIsNull() {
            addCriterion("DMP_ID_BRAINSPINETMLN is null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNIsNotNull() {
            addCriterion("DMP_ID_BRAINSPINETMLN is not null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN =", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNNotEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN <>", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNGreaterThan(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN >", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNGreaterThanOrEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN >=", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNLessThan(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN <", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNLessThanOrEqualTo(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN <=", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNLike(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN like", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNNotLike(String value) {
            addCriterion("DMP_ID_BRAINSPINETMLN not like", value, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNIn(List<String> values) {
            addCriterion("DMP_ID_BRAINSPINETMLN in", values, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNNotIn(List<String> values) {
            addCriterion("DMP_ID_BRAINSPINETMLN not in", values, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNBetween(String value1, String value2) {
            addCriterion("DMP_ID_BRAINSPINETMLN between", value1, value2, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_BRAINSPINETMLNNotBetween(String value1, String value2) {
            addCriterion("DMP_ID_BRAINSPINETMLN not between", value1, value2, "DMP_ID_BRAINSPINETMLN");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEEqualTo(String value) {
            addCriterion("START_DATE =", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATENotEqualTo(String value) {
            addCriterion("START_DATE <>", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEGreaterThan(String value) {
            addCriterion("START_DATE >", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEGreaterThanOrEqualTo(String value) {
            addCriterion("START_DATE >=", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATELessThan(String value) {
            addCriterion("START_DATE <", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATELessThanOrEqualTo(String value) {
            addCriterion("START_DATE <=", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATELike(String value) {
            addCriterion("START_DATE like", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATENotLike(String value) {
            addCriterion("START_DATE not like", value, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEIn(List<String> values) {
            addCriterion("START_DATE in", values, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATENotIn(List<String> values) {
            addCriterion("START_DATE not in", values, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATEBetween(String value1, String value2) {
            addCriterion("START_DATE between", value1, value2, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTART_DATENotBetween(String value1, String value2) {
            addCriterion("START_DATE not between", value1, value2, "START_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATEIsNull() {
            addCriterion("STOP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATEIsNotNull() {
            addCriterion("STOP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATEEqualTo(String value) {
            addCriterion("STOP_DATE =", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATENotEqualTo(String value) {
            addCriterion("STOP_DATE <>", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATEGreaterThan(String value) {
            addCriterion("STOP_DATE >", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATEGreaterThanOrEqualTo(String value) {
            addCriterion("STOP_DATE >=", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATELessThan(String value) {
            addCriterion("STOP_DATE <", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATELessThanOrEqualTo(String value) {
            addCriterion("STOP_DATE <=", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATELike(String value) {
            addCriterion("STOP_DATE like", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATENotLike(String value) {
            addCriterion("STOP_DATE not like", value, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATEIn(List<String> values) {
            addCriterion("STOP_DATE in", values, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATENotIn(List<String> values) {
            addCriterion("STOP_DATE not in", values, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATEBetween(String value1, String value2) {
            addCriterion("STOP_DATE between", value1, value2, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andSTOP_DATENotBetween(String value1, String value2) {
            addCriterion("STOP_DATE not between", value1, value2, "STOP_DATE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPEIsNull() {
            addCriterion("EVENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPEIsNotNull() {
            addCriterion("EVENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPEEqualTo(String value) {
            addCriterion("EVENT_TYPE =", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPENotEqualTo(String value) {
            addCriterion("EVENT_TYPE <>", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPEGreaterThan(String value) {
            addCriterion("EVENT_TYPE >", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("EVENT_TYPE >=", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPELessThan(String value) {
            addCriterion("EVENT_TYPE <", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPELessThanOrEqualTo(String value) {
            addCriterion("EVENT_TYPE <=", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPELike(String value) {
            addCriterion("EVENT_TYPE like", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPENotLike(String value) {
            addCriterion("EVENT_TYPE not like", value, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPEIn(List<String> values) {
            addCriterion("EVENT_TYPE in", values, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPENotIn(List<String> values) {
            addCriterion("EVENT_TYPE not in", values, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPEBetween(String value1, String value2) {
            addCriterion("EVENT_TYPE between", value1, value2, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andEVENT_TYPENotBetween(String value1, String value2) {
            addCriterion("EVENT_TYPE not between", value1, value2, "EVENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPEIsNull() {
            addCriterion("TREATMENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPEIsNotNull() {
            addCriterion("TREATMENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPEEqualTo(String value) {
            addCriterion("TREATMENT_TYPE =", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPENotEqualTo(String value) {
            addCriterion("TREATMENT_TYPE <>", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPEGreaterThan(String value) {
            addCriterion("TREATMENT_TYPE >", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("TREATMENT_TYPE >=", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPELessThan(String value) {
            addCriterion("TREATMENT_TYPE <", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPELessThanOrEqualTo(String value) {
            addCriterion("TREATMENT_TYPE <=", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPELike(String value) {
            addCriterion("TREATMENT_TYPE like", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPENotLike(String value) {
            addCriterion("TREATMENT_TYPE not like", value, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPEIn(List<String> values) {
            addCriterion("TREATMENT_TYPE in", values, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPENotIn(List<String> values) {
            addCriterion("TREATMENT_TYPE not in", values, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPEBetween(String value1, String value2) {
            addCriterion("TREATMENT_TYPE between", value1, value2, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTREATMENT_TYPENotBetween(String value1, String value2) {
            addCriterion("TREATMENT_TYPE not between", value1, value2, "TREATMENT_TYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPEIsNull() {
            addCriterion("SUBTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSUBTYPEIsNotNull() {
            addCriterion("SUBTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSUBTYPEEqualTo(String value) {
            addCriterion("SUBTYPE =", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPENotEqualTo(String value) {
            addCriterion("SUBTYPE <>", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPEGreaterThan(String value) {
            addCriterion("SUBTYPE >", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("SUBTYPE >=", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPELessThan(String value) {
            addCriterion("SUBTYPE <", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPELessThanOrEqualTo(String value) {
            addCriterion("SUBTYPE <=", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPELike(String value) {
            addCriterion("SUBTYPE like", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPENotLike(String value) {
            addCriterion("SUBTYPE not like", value, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPEIn(List<String> values) {
            addCriterion("SUBTYPE in", values, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPENotIn(List<String> values) {
            addCriterion("SUBTYPE not in", values, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPEBetween(String value1, String value2) {
            addCriterion("SUBTYPE between", value1, value2, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andSUBTYPENotBetween(String value1, String value2) {
            addCriterion("SUBTYPE not between", value1, value2, "SUBTYPE");
            return (Criteria) this;
        }

        public Criteria andAGENTIsNull() {
            addCriterion("AGENT is null");
            return (Criteria) this;
        }

        public Criteria andAGENTIsNotNull() {
            addCriterion("AGENT is not null");
            return (Criteria) this;
        }

        public Criteria andAGENTEqualTo(String value) {
            addCriterion("AGENT =", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTNotEqualTo(String value) {
            addCriterion("AGENT <>", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTGreaterThan(String value) {
            addCriterion("AGENT >", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTGreaterThanOrEqualTo(String value) {
            addCriterion("AGENT >=", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTLessThan(String value) {
            addCriterion("AGENT <", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTLessThanOrEqualTo(String value) {
            addCriterion("AGENT <=", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTLike(String value) {
            addCriterion("AGENT like", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTNotLike(String value) {
            addCriterion("AGENT not like", value, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTIn(List<String> values) {
            addCriterion("AGENT in", values, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTNotIn(List<String> values) {
            addCriterion("AGENT not in", values, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTBetween(String value1, String value2) {
            addCriterion("AGENT between", value1, value2, "AGENT");
            return (Criteria) this;
        }

        public Criteria andAGENTNotBetween(String value1, String value2) {
            addCriterion("AGENT not between", value1, value2, "AGENT");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERIsNull() {
            addCriterion("SPECIMENREFERENCENUMBER is null");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERIsNotNull() {
            addCriterion("SPECIMENREFERENCENUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBEREqualTo(String value) {
            addCriterion("SPECIMENREFERENCENUMBER =", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERNotEqualTo(String value) {
            addCriterion("SPECIMENREFERENCENUMBER <>", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERGreaterThan(String value) {
            addCriterion("SPECIMENREFERENCENUMBER >", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("SPECIMENREFERENCENUMBER >=", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERLessThan(String value) {
            addCriterion("SPECIMENREFERENCENUMBER <", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERLessThanOrEqualTo(String value) {
            addCriterion("SPECIMENREFERENCENUMBER <=", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERLike(String value) {
            addCriterion("SPECIMENREFERENCENUMBER like", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERNotLike(String value) {
            addCriterion("SPECIMENREFERENCENUMBER not like", value, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERIn(List<String> values) {
            addCriterion("SPECIMENREFERENCENUMBER in", values, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERNotIn(List<String> values) {
            addCriterion("SPECIMENREFERENCENUMBER not in", values, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERBetween(String value1, String value2) {
            addCriterion("SPECIMENREFERENCENUMBER between", value1, value2, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMENREFERENCENUMBERNotBetween(String value1, String value2) {
            addCriterion("SPECIMENREFERENCENUMBER not between", value1, value2, "SPECIMENREFERENCENUMBER");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITEIsNull() {
            addCriterion("SPECIMEN_SITE is null");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITEIsNotNull() {
            addCriterion("SPECIMEN_SITE is not null");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITEEqualTo(String value) {
            addCriterion("SPECIMEN_SITE =", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITENotEqualTo(String value) {
            addCriterion("SPECIMEN_SITE <>", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITEGreaterThan(String value) {
            addCriterion("SPECIMEN_SITE >", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITEGreaterThanOrEqualTo(String value) {
            addCriterion("SPECIMEN_SITE >=", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITELessThan(String value) {
            addCriterion("SPECIMEN_SITE <", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITELessThanOrEqualTo(String value) {
            addCriterion("SPECIMEN_SITE <=", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITELike(String value) {
            addCriterion("SPECIMEN_SITE like", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITENotLike(String value) {
            addCriterion("SPECIMEN_SITE not like", value, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITEIn(List<String> values) {
            addCriterion("SPECIMEN_SITE in", values, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITENotIn(List<String> values) {
            addCriterion("SPECIMEN_SITE not in", values, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITEBetween(String value1, String value2) {
            addCriterion("SPECIMEN_SITE between", value1, value2, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMEN_SITENotBetween(String value1, String value2) {
            addCriterion("SPECIMEN_SITE not between", value1, value2, "SPECIMEN_SITE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPEIsNull() {
            addCriterion("SPECIMENTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPEIsNotNull() {
            addCriterion("SPECIMENTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPEEqualTo(String value) {
            addCriterion("SPECIMENTYPE =", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPENotEqualTo(String value) {
            addCriterion("SPECIMENTYPE <>", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPEGreaterThan(String value) {
            addCriterion("SPECIMENTYPE >", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("SPECIMENTYPE >=", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPELessThan(String value) {
            addCriterion("SPECIMENTYPE <", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPELessThanOrEqualTo(String value) {
            addCriterion("SPECIMENTYPE <=", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPELike(String value) {
            addCriterion("SPECIMENTYPE like", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPENotLike(String value) {
            addCriterion("SPECIMENTYPE not like", value, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPEIn(List<String> values) {
            addCriterion("SPECIMENTYPE in", values, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPENotIn(List<String> values) {
            addCriterion("SPECIMENTYPE not in", values, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPEBetween(String value1, String value2) {
            addCriterion("SPECIMENTYPE between", value1, value2, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSPECIMENTYPENotBetween(String value1, String value2) {
            addCriterion("SPECIMENTYPE not between", value1, value2, "SPECIMENTYPE");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONIsNull() {
            addCriterion("EVENT_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONIsNotNull() {
            addCriterion("EVENT_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONEqualTo(String value) {
            addCriterion("EVENT_LOCATION =", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONNotEqualTo(String value) {
            addCriterion("EVENT_LOCATION <>", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONGreaterThan(String value) {
            addCriterion("EVENT_LOCATION >", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONGreaterThanOrEqualTo(String value) {
            addCriterion("EVENT_LOCATION >=", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONLessThan(String value) {
            addCriterion("EVENT_LOCATION <", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONLessThanOrEqualTo(String value) {
            addCriterion("EVENT_LOCATION <=", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONLike(String value) {
            addCriterion("EVENT_LOCATION like", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONNotLike(String value) {
            addCriterion("EVENT_LOCATION not like", value, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONIn(List<String> values) {
            addCriterion("EVENT_LOCATION in", values, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONNotIn(List<String> values) {
            addCriterion("EVENT_LOCATION not in", values, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONBetween(String value1, String value2) {
            addCriterion("EVENT_LOCATION between", value1, value2, "EVENT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andEVENT_LOCATIONNotBetween(String value1, String value2) {
            addCriterion("EVENT_LOCATION not between", value1, value2, "EVENT_LOCATION");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.DMT_TIMELINE_BRAINSPINE_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}