package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

import java.util.ArrayList;
import java.util.List;

public class PatientMedOrder2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public PatientMedOrder2Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDIsNull() {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDIsNotNull() {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDEqualTo(Integer value) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID =", value, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDNotEqualTo(Integer value) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID <>", value, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDGreaterThan(Integer value) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID >", value, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID >=", value, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDLessThan(Integer value) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID <", value, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDLessThanOrEqualTo(Integer value) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID <=", value, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDIn(List<Integer> values) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID in", values, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDNotIn(List<Integer> values) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID not in", values, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDBetween(Integer value1, Integer value2) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID between", value1, value2, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_PT_DEIDENTIFICATION_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("ORD_PT_DEIDENTIFICATION_ID not between", value1, value2, "ORD_PT_DEIDENTIFICATION_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDIsNull() {
            addCriterion("ORD_DMP_PT_ID is null");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDIsNotNull() {
            addCriterion("ORD_DMP_PT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDEqualTo(String value) {
            addCriterion("ORD_DMP_PT_ID =", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDNotEqualTo(String value) {
            addCriterion("ORD_DMP_PT_ID <>", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDGreaterThan(String value) {
            addCriterion("ORD_DMP_PT_ID >", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDGreaterThanOrEqualTo(String value) {
            addCriterion("ORD_DMP_PT_ID >=", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDLessThan(String value) {
            addCriterion("ORD_DMP_PT_ID <", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDLessThanOrEqualTo(String value) {
            addCriterion("ORD_DMP_PT_ID <=", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDLike(String value) {
            addCriterion("ORD_DMP_PT_ID like", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDNotLike(String value) {
            addCriterion("ORD_DMP_PT_ID not like", value, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDIn(List<String> values) {
            addCriterion("ORD_DMP_PT_ID in", values, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDNotIn(List<String> values) {
            addCriterion("ORD_DMP_PT_ID not in", values, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDBetween(String value1, String value2) {
            addCriterion("ORD_DMP_PT_ID between", value1, value2, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_DMP_PT_IDNotBetween(String value1, String value2) {
            addCriterion("ORD_DMP_PT_ID not between", value1, value2, "ORD_DMP_PT_ID");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATIsNull() {
            addCriterion("ORD_THERAPEUTIC_CAT is null");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATIsNotNull() {
            addCriterion("ORD_THERAPEUTIC_CAT is not null");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATEqualTo(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT =", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATNotEqualTo(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT <>", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATGreaterThan(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT >", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATGreaterThanOrEqualTo(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT >=", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATLessThan(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT <", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATLessThanOrEqualTo(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT <=", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATLike(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT like", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATNotLike(String value) {
            addCriterion("ORD_THERAPEUTIC_CAT not like", value, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATIn(List<String> values) {
            addCriterion("ORD_THERAPEUTIC_CAT in", values, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATNotIn(List<String> values) {
            addCriterion("ORD_THERAPEUTIC_CAT not in", values, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATBetween(String value1, String value2) {
            addCriterion("ORD_THERAPEUTIC_CAT between", value1, value2, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_THERAPEUTIC_CATNotBetween(String value1, String value2) {
            addCriterion("ORD_THERAPEUTIC_CAT not between", value1, value2, "ORD_THERAPEUTIC_CAT");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMEIsNull() {
            addCriterion("ORD_SET_NAME is null");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMEIsNotNull() {
            addCriterion("ORD_SET_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMEEqualTo(String value) {
            addCriterion("ORD_SET_NAME =", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMENotEqualTo(String value) {
            addCriterion("ORD_SET_NAME <>", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMEGreaterThan(String value) {
            addCriterion("ORD_SET_NAME >", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ORD_SET_NAME >=", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMELessThan(String value) {
            addCriterion("ORD_SET_NAME <", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMELessThanOrEqualTo(String value) {
            addCriterion("ORD_SET_NAME <=", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMELike(String value) {
            addCriterion("ORD_SET_NAME like", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMENotLike(String value) {
            addCriterion("ORD_SET_NAME not like", value, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMEIn(List<String> values) {
            addCriterion("ORD_SET_NAME in", values, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMENotIn(List<String> values) {
            addCriterion("ORD_SET_NAME not in", values, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMEBetween(String value1, String value2) {
            addCriterion("ORD_SET_NAME between", value1, value2, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_SET_NAMENotBetween(String value1, String value2) {
            addCriterion("ORD_SET_NAME not between", value1, value2, "ORD_SET_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMEIsNull() {
            addCriterion("ORD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andORD_NAMEIsNotNull() {
            addCriterion("ORD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andORD_NAMEEqualTo(String value) {
            addCriterion("ORD_NAME =", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMENotEqualTo(String value) {
            addCriterion("ORD_NAME <>", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMEGreaterThan(String value) {
            addCriterion("ORD_NAME >", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ORD_NAME >=", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMELessThan(String value) {
            addCriterion("ORD_NAME <", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMELessThanOrEqualTo(String value) {
            addCriterion("ORD_NAME <=", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMELike(String value) {
            addCriterion("ORD_NAME like", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMENotLike(String value) {
            addCriterion("ORD_NAME not like", value, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMEIn(List<String> values) {
            addCriterion("ORD_NAME in", values, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMENotIn(List<String> values) {
            addCriterion("ORD_NAME not in", values, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMEBetween(String value1, String value2) {
            addCriterion("ORD_NAME between", value1, value2, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_NAMENotBetween(String value1, String value2) {
            addCriterion("ORD_NAME not between", value1, value2, "ORD_NAME");
            return (Criteria) this;
        }

        public Criteria andORD_DESCIsNull() {
            addCriterion("ORD_DESC is null");
            return (Criteria) this;
        }

        public Criteria andORD_DESCIsNotNull() {
            addCriterion("ORD_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andORD_DESCEqualTo(String value) {
            addCriterion("ORD_DESC =", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCNotEqualTo(String value) {
            addCriterion("ORD_DESC <>", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCGreaterThan(String value) {
            addCriterion("ORD_DESC >", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCGreaterThanOrEqualTo(String value) {
            addCriterion("ORD_DESC >=", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCLessThan(String value) {
            addCriterion("ORD_DESC <", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCLessThanOrEqualTo(String value) {
            addCriterion("ORD_DESC <=", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCLike(String value) {
            addCriterion("ORD_DESC like", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCNotLike(String value) {
            addCriterion("ORD_DESC not like", value, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCIn(List<String> values) {
            addCriterion("ORD_DESC in", values, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCNotIn(List<String> values) {
            addCriterion("ORD_DESC not in", values, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCBetween(String value1, String value2) {
            addCriterion("ORD_DESC between", value1, value2, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_DESCNotBetween(String value1, String value2) {
            addCriterion("ORD_DESC not between", value1, value2, "ORD_DESC");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINEIsNull() {
            addCriterion("ORD_SUMMARY_LINE is null");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINEIsNotNull() {
            addCriterion("ORD_SUMMARY_LINE is not null");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINEEqualTo(String value) {
            addCriterion("ORD_SUMMARY_LINE =", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINENotEqualTo(String value) {
            addCriterion("ORD_SUMMARY_LINE <>", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINEGreaterThan(String value) {
            addCriterion("ORD_SUMMARY_LINE >", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINEGreaterThanOrEqualTo(String value) {
            addCriterion("ORD_SUMMARY_LINE >=", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINELessThan(String value) {
            addCriterion("ORD_SUMMARY_LINE <", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINELessThanOrEqualTo(String value) {
            addCriterion("ORD_SUMMARY_LINE <=", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINELike(String value) {
            addCriterion("ORD_SUMMARY_LINE like", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINENotLike(String value) {
            addCriterion("ORD_SUMMARY_LINE not like", value, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINEIn(List<String> values) {
            addCriterion("ORD_SUMMARY_LINE in", values, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINENotIn(List<String> values) {
            addCriterion("ORD_SUMMARY_LINE not in", values, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINEBetween(String value1, String value2) {
            addCriterion("ORD_SUMMARY_LINE between", value1, value2, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andORD_SUMMARY_LINENotBetween(String value1, String value2) {
            addCriterion("ORD_SUMMARY_LINE not between", value1, value2, "ORD_SUMMARY_LINE");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSIsNull() {
            addCriterion("AGE_AT_ORDER_IN_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSIsNotNull() {
            addCriterion("AGE_AT_ORDER_IN_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSEqualTo(Integer value) {
            addCriterion("AGE_AT_ORDER_IN_DAYS =", value, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSNotEqualTo(Integer value) {
            addCriterion("AGE_AT_ORDER_IN_DAYS <>", value, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSGreaterThan(Integer value) {
            addCriterion("AGE_AT_ORDER_IN_DAYS >", value, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_ORDER_IN_DAYS >=", value, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSLessThan(Integer value) {
            addCriterion("AGE_AT_ORDER_IN_DAYS <", value, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSLessThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_ORDER_IN_DAYS <=", value, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSIn(List<Integer> values) {
            addCriterion("AGE_AT_ORDER_IN_DAYS in", values, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSNotIn(List<Integer> values) {
            addCriterion("AGE_AT_ORDER_IN_DAYS not in", values, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_ORDER_IN_DAYS between", value1, value2, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ORDER_IN_DAYSNotBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_ORDER_IN_DAYS not between", value1, value2, "AGE_AT_ORDER_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andORD_YEARIsNull() {
            addCriterion("ORD_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andORD_YEARIsNotNull() {
            addCriterion("ORD_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andORD_YEAREqualTo(Integer value) {
            addCriterion("ORD_YEAR =", value, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARNotEqualTo(Integer value) {
            addCriterion("ORD_YEAR <>", value, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARGreaterThan(Integer value) {
            addCriterion("ORD_YEAR >", value, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORD_YEAR >=", value, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARLessThan(Integer value) {
            addCriterion("ORD_YEAR <", value, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARLessThanOrEqualTo(Integer value) {
            addCriterion("ORD_YEAR <=", value, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARIn(List<Integer> values) {
            addCriterion("ORD_YEAR in", values, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARNotIn(List<Integer> values) {
            addCriterion("ORD_YEAR not in", values, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARBetween(Integer value1, Integer value2) {
            addCriterion("ORD_YEAR between", value1, value2, "ORD_YEAR");
            return (Criteria) this;
        }

        public Criteria andORD_YEARNotBetween(Integer value1, Integer value2) {
            addCriterion("ORD_YEAR not between", value1, value2, "ORD_YEAR");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.MED_ORDER_V2
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}