package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

import java.math.BigDecimal;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PatientLabResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public PatientLabResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<Time> timeList = new ArrayList<Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andPT_ID_LABIsNull() {
            addCriterion("PT_ID_LAB is null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABIsNotNull() {
            addCriterion("PT_ID_LAB is not null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABEqualTo(Integer value) {
            addCriterion("PT_ID_LAB =", value, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABNotEqualTo(Integer value) {
            addCriterion("PT_ID_LAB <>", value, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABGreaterThan(Integer value) {
            addCriterion("PT_ID_LAB >", value, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABGreaterThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_LAB >=", value, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABLessThan(Integer value) {
            addCriterion("PT_ID_LAB <", value, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABLessThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_LAB <=", value, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABIn(List<Integer> values) {
            addCriterion("PT_ID_LAB in", values, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABNotIn(List<Integer> values) {
            addCriterion("PT_ID_LAB not in", values, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABBetween(Integer value1, Integer value2) {
            addCriterion("PT_ID_LAB between", value1, value2, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andPT_ID_LABNotBetween(Integer value1, Integer value2) {
            addCriterion("PT_ID_LAB not between", value1, value2, "PT_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABIsNull() {
            addCriterion("DMP_ID_LAB is null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABIsNotNull() {
            addCriterion("DMP_ID_LAB is not null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABEqualTo(String value) {
            addCriterion("DMP_ID_LAB =", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABNotEqualTo(String value) {
            addCriterion("DMP_ID_LAB <>", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABGreaterThan(String value) {
            addCriterion("DMP_ID_LAB >", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABGreaterThanOrEqualTo(String value) {
            addCriterion("DMP_ID_LAB >=", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABLessThan(String value) {
            addCriterion("DMP_ID_LAB <", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABLessThanOrEqualTo(String value) {
            addCriterion("DMP_ID_LAB <=", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABLike(String value) {
            addCriterion("DMP_ID_LAB like", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABNotLike(String value) {
            addCriterion("DMP_ID_LAB not like", value, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABIn(List<String> values) {
            addCriterion("DMP_ID_LAB in", values, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABNotIn(List<String> values) {
            addCriterion("DMP_ID_LAB not in", values, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABBetween(String value1, String value2) {
            addCriterion("DMP_ID_LAB between", value1, value2, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_LABNotBetween(String value1, String value2) {
            addCriterion("DMP_ID_LAB not between", value1, value2, "DMP_ID_LAB");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMEIsNull() {
            addCriterion("LAB_TEST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMEIsNotNull() {
            addCriterion("LAB_TEST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMEEqualTo(String value) {
            addCriterion("LAB_TEST_NAME =", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMENotEqualTo(String value) {
            addCriterion("LAB_TEST_NAME <>", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMEGreaterThan(String value) {
            addCriterion("LAB_TEST_NAME >", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_NAME >=", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMELessThan(String value) {
            addCriterion("LAB_TEST_NAME <", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMELessThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_NAME <=", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMELike(String value) {
            addCriterion("LAB_TEST_NAME like", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMENotLike(String value) {
            addCriterion("LAB_TEST_NAME not like", value, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMEIn(List<String> values) {
            addCriterion("LAB_TEST_NAME in", values, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMENotIn(List<String> values) {
            addCriterion("LAB_TEST_NAME not in", values, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMEBetween(String value1, String value2) {
            addCriterion("LAB_TEST_NAME between", value1, value2, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_NAMENotBetween(String value1, String value2) {
            addCriterion("LAB_TEST_NAME not between", value1, value2, "LAB_TEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMEIsNull() {
            addCriterion("LAB_SUBTEST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMEIsNotNull() {
            addCriterion("LAB_SUBTEST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMEEqualTo(String value) {
            addCriterion("LAB_SUBTEST_NAME =", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMENotEqualTo(String value) {
            addCriterion("LAB_SUBTEST_NAME <>", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMEGreaterThan(String value) {
            addCriterion("LAB_SUBTEST_NAME >", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_SUBTEST_NAME >=", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMELessThan(String value) {
            addCriterion("LAB_SUBTEST_NAME <", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMELessThanOrEqualTo(String value) {
            addCriterion("LAB_SUBTEST_NAME <=", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMELike(String value) {
            addCriterion("LAB_SUBTEST_NAME like", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMENotLike(String value) {
            addCriterion("LAB_SUBTEST_NAME not like", value, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMEIn(List<String> values) {
            addCriterion("LAB_SUBTEST_NAME in", values, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMENotIn(List<String> values) {
            addCriterion("LAB_SUBTEST_NAME not in", values, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMEBetween(String value1, String value2) {
            addCriterion("LAB_SUBTEST_NAME between", value1, value2, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_NAMENotBetween(String value1, String value2) {
            addCriterion("LAB_SUBTEST_NAME not between", value1, value2, "LAB_SUBTEST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYIsNull() {
            addCriterion("LAB_TEST_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYIsNotNull() {
            addCriterion("LAB_TEST_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYEqualTo(String value) {
            addCriterion("LAB_TEST_CATEGORY =", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYNotEqualTo(String value) {
            addCriterion("LAB_TEST_CATEGORY <>", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYGreaterThan(String value) {
            addCriterion("LAB_TEST_CATEGORY >", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_CATEGORY >=", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYLessThan(String value) {
            addCriterion("LAB_TEST_CATEGORY <", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYLessThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_CATEGORY <=", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYLike(String value) {
            addCriterion("LAB_TEST_CATEGORY like", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYNotLike(String value) {
            addCriterion("LAB_TEST_CATEGORY not like", value, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYIn(List<String> values) {
            addCriterion("LAB_TEST_CATEGORY in", values, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYNotIn(List<String> values) {
            addCriterion("LAB_TEST_CATEGORY not in", values, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYBetween(String value1, String value2) {
            addCriterion("LAB_TEST_CATEGORY between", value1, value2, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_CATEGORYNotBetween(String value1, String value2) {
            addCriterion("LAB_TEST_CATEGORY not between", value1, value2, "LAB_TEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYIsNull() {
            addCriterion("LAB_SUBTEST_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYIsNotNull() {
            addCriterion("LAB_SUBTEST_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYEqualTo(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY =", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYNotEqualTo(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY <>", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYGreaterThan(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY >", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY >=", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYLessThan(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY <", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYLessThanOrEqualTo(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY <=", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYLike(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY like", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYNotLike(String value) {
            addCriterion("LAB_SUBTEST_CATEGORY not like", value, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYIn(List<String> values) {
            addCriterion("LAB_SUBTEST_CATEGORY in", values, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYNotIn(List<String> values) {
            addCriterion("LAB_SUBTEST_CATEGORY not in", values, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYBetween(String value1, String value2) {
            addCriterion("LAB_SUBTEST_CATEGORY between", value1, value2, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_SUBTEST_CATEGORYNotBetween(String value1, String value2) {
            addCriterion("LAB_SUBTEST_CATEGORY not between", value1, value2, "LAB_SUBTEST_CATEGORY");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARIsNull() {
            addCriterion("LAB_PERFORMED_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARIsNotNull() {
            addCriterion("LAB_PERFORMED_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEAREqualTo(Short value) {
            addCriterion("LAB_PERFORMED_YEAR =", value, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARNotEqualTo(Short value) {
            addCriterion("LAB_PERFORMED_YEAR <>", value, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARGreaterThan(Short value) {
            addCriterion("LAB_PERFORMED_YEAR >", value, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("LAB_PERFORMED_YEAR >=", value, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARLessThan(Short value) {
            addCriterion("LAB_PERFORMED_YEAR <", value, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARLessThanOrEqualTo(Short value) {
            addCriterion("LAB_PERFORMED_YEAR <=", value, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARIn(List<Short> values) {
            addCriterion("LAB_PERFORMED_YEAR in", values, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARNotIn(List<Short> values) {
            addCriterion("LAB_PERFORMED_YEAR not in", values, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARBetween(Short value1, Short value2) {
            addCriterion("LAB_PERFORMED_YEAR between", value1, value2, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_YEARNotBetween(Short value1, Short value2) {
            addCriterion("LAB_PERFORMED_YEAR not between", value1, value2, "LAB_PERFORMED_YEAR");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSIsNull() {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSIsNotNull() {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS =", value, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSNotEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS <>", value, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSGreaterThan(Integer value) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS >", value, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS >=", value, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSLessThan(Integer value) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS <", value, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSLessThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS <=", value, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSIn(List<Integer> values) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS in", values, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSNotIn(List<Integer> values) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS not in", values, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS between", value1, value2, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_PERFORMED_DATE_IN_DAYSNotBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_LAB_PERFORMED_DATE_IN_DAYS not between", value1, value2, "AGE_AT_LAB_PERFORMED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMEIsNull() {
            addCriterion("LAB_PERFORMED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMEIsNotNull() {
            addCriterion("LAB_PERFORMED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMEEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME =", value, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMENotEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME <>", value, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMEGreaterThan(Date value) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME >", value, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME >=", value, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMELessThan(Date value) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME <", value, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMELessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME <=", value, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMEIn(List<Date> values) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME in", values, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMENotIn(List<Date> values) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME not in", values, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMEBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME between", value1, value2, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_PERFORMED_TIMENotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("LAB_PERFORMED_TIME not between", value1, value2, "LAB_PERFORMED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARIsNull() {
            addCriterion("LAB_ENTERED_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARIsNotNull() {
            addCriterion("LAB_ENTERED_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEAREqualTo(Short value) {
            addCriterion("LAB_ENTERED_YEAR =", value, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARNotEqualTo(Short value) {
            addCriterion("LAB_ENTERED_YEAR <>", value, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARGreaterThan(Short value) {
            addCriterion("LAB_ENTERED_YEAR >", value, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("LAB_ENTERED_YEAR >=", value, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARLessThan(Short value) {
            addCriterion("LAB_ENTERED_YEAR <", value, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARLessThanOrEqualTo(Short value) {
            addCriterion("LAB_ENTERED_YEAR <=", value, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARIn(List<Short> values) {
            addCriterion("LAB_ENTERED_YEAR in", values, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARNotIn(List<Short> values) {
            addCriterion("LAB_ENTERED_YEAR not in", values, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARBetween(Short value1, Short value2) {
            addCriterion("LAB_ENTERED_YEAR between", value1, value2, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_YEARNotBetween(Short value1, Short value2) {
            addCriterion("LAB_ENTERED_YEAR not between", value1, value2, "LAB_ENTERED_YEAR");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSIsNull() {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSIsNotNull() {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS =", value, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSNotEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS <>", value, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSGreaterThan(Integer value) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS >", value, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS >=", value, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSLessThan(Integer value) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS <", value, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSLessThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS <=", value, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSIn(List<Integer> values) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS in", values, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSNotIn(List<Integer> values) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS not in", values, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS between", value1, value2, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_LAB_ENTERED_DATE_IN_DAYSNotBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_LAB_ENTERED_DATE_IN_DAYS not between", value1, value2, "AGE_AT_LAB_ENTERED_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMEIsNull() {
            addCriterion("LAB_ENTERED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMEIsNotNull() {
            addCriterion("LAB_ENTERED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMEEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME =", value, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMENotEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME <>", value, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMEGreaterThan(Date value) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME >", value, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME >=", value, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMELessThan(Date value) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME <", value, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMELessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME <=", value, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMEIn(List<Date> values) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME in", values, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMENotIn(List<Date> values) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME not in", values, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMEBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME between", value1, value2, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_ENTERED_TIMENotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("LAB_ENTERED_TIME not between", value1, value2, "LAB_ENTERED_TIME");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESIsNull() {
            addCriterion("LAB_TEST_RESULT_NOTES is null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESIsNotNull() {
            addCriterion("LAB_TEST_RESULT_NOTES is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES =", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESNotEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES <>", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESGreaterThan(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES >", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES >=", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESLessThan(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES <", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESLessThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES <=", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESLike(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES like", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESNotLike(String value) {
            addCriterion("LAB_TEST_RESULT_NOTES not like", value, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESIn(List<String> values) {
            addCriterion("LAB_TEST_RESULT_NOTES in", values, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESNotIn(List<String> values) {
            addCriterion("LAB_TEST_RESULT_NOTES not in", values, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESBetween(String value1, String value2) {
            addCriterion("LAB_TEST_RESULT_NOTES between", value1, value2, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_NOTESNotBetween(String value1, String value2) {
            addCriterion("LAB_TEST_RESULT_NOTES not between", value1, value2, "LAB_TEST_RESULT_NOTES");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUEIsNull() {
            addCriterion("LAB_TEST_RESULT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUEIsNotNull() {
            addCriterion("LAB_TEST_RESULT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUEEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE =", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUENotEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE <>", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUEGreaterThan(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE >", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUEGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE >=", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUELessThan(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE <", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUELessThanOrEqualTo(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE <=", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUELike(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE like", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUENotLike(String value) {
            addCriterion("LAB_TEST_RESULT_VALUE not like", value, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUEIn(List<String> values) {
            addCriterion("LAB_TEST_RESULT_VALUE in", values, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUENotIn(List<String> values) {
            addCriterion("LAB_TEST_RESULT_VALUE not in", values, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUEBetween(String value1, String value2) {
            addCriterion("LAB_TEST_RESULT_VALUE between", value1, value2, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_TEST_RESULT_VALUENotBetween(String value1, String value2) {
            addCriterion("LAB_TEST_RESULT_VALUE not between", value1, value2, "LAB_TEST_RESULT_VALUE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASUREIsNull() {
            addCriterion("LAB_UNIT_MEASURE is null");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASUREIsNotNull() {
            addCriterion("LAB_UNIT_MEASURE is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASUREEqualTo(String value) {
            addCriterion("LAB_UNIT_MEASURE =", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASURENotEqualTo(String value) {
            addCriterion("LAB_UNIT_MEASURE <>", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASUREGreaterThan(String value) {
            addCriterion("LAB_UNIT_MEASURE >", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASUREGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_UNIT_MEASURE >=", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASURELessThan(String value) {
            addCriterion("LAB_UNIT_MEASURE <", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASURELessThanOrEqualTo(String value) {
            addCriterion("LAB_UNIT_MEASURE <=", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASURELike(String value) {
            addCriterion("LAB_UNIT_MEASURE like", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASURENotLike(String value) {
            addCriterion("LAB_UNIT_MEASURE not like", value, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASUREIn(List<String> values) {
            addCriterion("LAB_UNIT_MEASURE in", values, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASURENotIn(List<String> values) {
            addCriterion("LAB_UNIT_MEASURE not in", values, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASUREBetween(String value1, String value2) {
            addCriterion("LAB_UNIT_MEASURE between", value1, value2, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_UNIT_MEASURENotBetween(String value1, String value2) {
            addCriterion("LAB_UNIT_MEASURE not between", value1, value2, "LAB_UNIT_MEASURE");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGIsNull() {
            addCriterion("LAB_ABNORMAL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGIsNotNull() {
            addCriterion("LAB_ABNORMAL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGEqualTo(String value) {
            addCriterion("LAB_ABNORMAL_FLAG =", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGNotEqualTo(String value) {
            addCriterion("LAB_ABNORMAL_FLAG <>", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGGreaterThan(String value) {
            addCriterion("LAB_ABNORMAL_FLAG >", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_ABNORMAL_FLAG >=", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGLessThan(String value) {
            addCriterion("LAB_ABNORMAL_FLAG <", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGLessThanOrEqualTo(String value) {
            addCriterion("LAB_ABNORMAL_FLAG <=", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGLike(String value) {
            addCriterion("LAB_ABNORMAL_FLAG like", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGNotLike(String value) {
            addCriterion("LAB_ABNORMAL_FLAG not like", value, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGIn(List<String> values) {
            addCriterion("LAB_ABNORMAL_FLAG in", values, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGNotIn(List<String> values) {
            addCriterion("LAB_ABNORMAL_FLAG not in", values, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGBetween(String value1, String value2) {
            addCriterion("LAB_ABNORMAL_FLAG between", value1, value2, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_ABNORMAL_FLAGNotBetween(String value1, String value2) {
            addCriterion("LAB_ABNORMAL_FLAG not between", value1, value2, "LAB_ABNORMAL_FLAG");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERIsNull() {
            addCriterion("LAB_LIMIT_UPPER is null");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERIsNotNull() {
            addCriterion("LAB_LIMIT_UPPER is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPEREqualTo(String value) {
            addCriterion("LAB_LIMIT_UPPER =", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERNotEqualTo(String value) {
            addCriterion("LAB_LIMIT_UPPER <>", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERGreaterThan(String value) {
            addCriterion("LAB_LIMIT_UPPER >", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_LIMIT_UPPER >=", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERLessThan(String value) {
            addCriterion("LAB_LIMIT_UPPER <", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERLessThanOrEqualTo(String value) {
            addCriterion("LAB_LIMIT_UPPER <=", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERLike(String value) {
            addCriterion("LAB_LIMIT_UPPER like", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERNotLike(String value) {
            addCriterion("LAB_LIMIT_UPPER not like", value, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERIn(List<String> values) {
            addCriterion("LAB_LIMIT_UPPER in", values, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERNotIn(List<String> values) {
            addCriterion("LAB_LIMIT_UPPER not in", values, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERBetween(String value1, String value2) {
            addCriterion("LAB_LIMIT_UPPER between", value1, value2, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_UPPERNotBetween(String value1, String value2) {
            addCriterion("LAB_LIMIT_UPPER not between", value1, value2, "LAB_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERIsNull() {
            addCriterion("LAB_LIMIT_LOWER is null");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERIsNotNull() {
            addCriterion("LAB_LIMIT_LOWER is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWEREqualTo(String value) {
            addCriterion("LAB_LIMIT_LOWER =", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERNotEqualTo(String value) {
            addCriterion("LAB_LIMIT_LOWER <>", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERGreaterThan(String value) {
            addCriterion("LAB_LIMIT_LOWER >", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_LIMIT_LOWER >=", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERLessThan(String value) {
            addCriterion("LAB_LIMIT_LOWER <", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERLessThanOrEqualTo(String value) {
            addCriterion("LAB_LIMIT_LOWER <=", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERLike(String value) {
            addCriterion("LAB_LIMIT_LOWER like", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERNotLike(String value) {
            addCriterion("LAB_LIMIT_LOWER not like", value, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERIn(List<String> values) {
            addCriterion("LAB_LIMIT_LOWER in", values, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERNotIn(List<String> values) {
            addCriterion("LAB_LIMIT_LOWER not in", values, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERBetween(String value1, String value2) {
            addCriterion("LAB_LIMIT_LOWER between", value1, value2, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_LIMIT_LOWERNotBetween(String value1, String value2) {
            addCriterion("LAB_LIMIT_LOWER not between", value1, value2, "LAB_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORIsNull() {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORIsNotNull() {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATOREqualTo(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR =", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORNotEqualTo(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR <>", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORGreaterThan(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR >", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR >=", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORLessThan(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR <", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORLessThanOrEqualTo(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR <=", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORLike(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR like", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORNotLike(String value) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR not like", value, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORIn(List<String> values) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR in", values, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORNotIn(List<String> values) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR not in", values, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORBetween(String value1, String value2) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR between", value1, value2, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_INDICATORNotBetween(String value1, String value2) {
            addCriterion("LAB_PURE_NUMERIC_INDICATOR not between", value1, value2, "LAB_PURE_NUMERIC_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTIsNull() {
            addCriterion("LAB_PURE_NUMERIC_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTIsNotNull() {
            addCriterion("LAB_PURE_NUMERIC_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTEqualTo(BigDecimal value) {
            addCriterion("LAB_PURE_NUMERIC_RESULT =", value, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTNotEqualTo(BigDecimal value) {
            addCriterion("LAB_PURE_NUMERIC_RESULT <>", value, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTGreaterThan(BigDecimal value) {
            addCriterion("LAB_PURE_NUMERIC_RESULT >", value, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PURE_NUMERIC_RESULT >=", value, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTLessThan(BigDecimal value) {
            addCriterion("LAB_PURE_NUMERIC_RESULT <", value, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PURE_NUMERIC_RESULT <=", value, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTIn(List<BigDecimal> values) {
            addCriterion("LAB_PURE_NUMERIC_RESULT in", values, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTNotIn(List<BigDecimal> values) {
            addCriterion("LAB_PURE_NUMERIC_RESULT not in", values, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PURE_NUMERIC_RESULT between", value1, value2, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PURE_NUMERIC_RESULTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PURE_NUMERIC_RESULT not between", value1, value2, "LAB_PURE_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORIsNull() {
            addCriterion("LAB_GREATER_THAN_INDICATOR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORIsNotNull() {
            addCriterion("LAB_GREATER_THAN_INDICATOR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATOREqualTo(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR =", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORNotEqualTo(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR <>", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORGreaterThan(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR >", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR >=", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORLessThan(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR <", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORLessThanOrEqualTo(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR <=", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORLike(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR like", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORNotLike(String value) {
            addCriterion("LAB_GREATER_THAN_INDICATOR not like", value, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORIn(List<String> values) {
            addCriterion("LAB_GREATER_THAN_INDICATOR in", values, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORNotIn(List<String> values) {
            addCriterion("LAB_GREATER_THAN_INDICATOR not in", values, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORBetween(String value1, String value2) {
            addCriterion("LAB_GREATER_THAN_INDICATOR between", value1, value2, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_GREATER_THAN_INDICATORNotBetween(String value1, String value2) {
            addCriterion("LAB_GREATER_THAN_INDICATOR not between", value1, value2, "LAB_GREATER_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORIsNull() {
            addCriterion("LAB_LESS_THAN_INDICATOR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORIsNotNull() {
            addCriterion("LAB_LESS_THAN_INDICATOR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATOREqualTo(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR =", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORNotEqualTo(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR <>", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORGreaterThan(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR >", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR >=", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORLessThan(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR <", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORLessThanOrEqualTo(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR <=", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORLike(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR like", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORNotLike(String value) {
            addCriterion("LAB_LESS_THAN_INDICATOR not like", value, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORIn(List<String> values) {
            addCriterion("LAB_LESS_THAN_INDICATOR in", values, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORNotIn(List<String> values) {
            addCriterion("LAB_LESS_THAN_INDICATOR not in", values, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORBetween(String value1, String value2) {
            addCriterion("LAB_LESS_THAN_INDICATOR between", value1, value2, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_LESS_THAN_INDICATORNotBetween(String value1, String value2) {
            addCriterion("LAB_LESS_THAN_INDICATOR not between", value1, value2, "LAB_LESS_THAN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERIsNull() {
            addCriterion("LAB_PARSED_LIMIT_LOWER is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERIsNotNull() {
            addCriterion("LAB_PARSED_LIMIT_LOWER is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWEREqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_LOWER =", value, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERNotEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_LOWER <>", value, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERGreaterThan(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_LOWER >", value, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_LOWER >=", value, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERLessThan(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_LOWER <", value, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_LOWER <=", value, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERIn(List<BigDecimal> values) {
            addCriterion("LAB_PARSED_LIMIT_LOWER in", values, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERNotIn(List<BigDecimal> values) {
            addCriterion("LAB_PARSED_LIMIT_LOWER not in", values, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PARSED_LIMIT_LOWER between", value1, value2, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_LOWERNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PARSED_LIMIT_LOWER not between", value1, value2, "LAB_PARSED_LIMIT_LOWER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTIsNull() {
            addCriterion("LAB_PARSED_NUMERIC_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTIsNotNull() {
            addCriterion("LAB_PARSED_NUMERIC_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT =", value, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTNotEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT <>", value, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTGreaterThan(BigDecimal value) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT >", value, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT >=", value, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTLessThan(BigDecimal value) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT <", value, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT <=", value, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTIn(List<BigDecimal> values) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT in", values, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTNotIn(List<BigDecimal> values) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT not in", values, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT between", value1, value2, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_NUMERIC_RESULTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PARSED_NUMERIC_RESULT not between", value1, value2, "LAB_PARSED_NUMERIC_RESULT");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERIsNull() {
            addCriterion("LAB_PARSED_LIMIT_UPPER is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERIsNotNull() {
            addCriterion("LAB_PARSED_LIMIT_UPPER is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPEREqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_UPPER =", value, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERNotEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_UPPER <>", value, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERGreaterThan(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_UPPER >", value, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_UPPER >=", value, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERLessThan(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_UPPER <", value, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAB_PARSED_LIMIT_UPPER <=", value, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERIn(List<BigDecimal> values) {
            addCriterion("LAB_PARSED_LIMIT_UPPER in", values, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERNotIn(List<BigDecimal> values) {
            addCriterion("LAB_PARSED_LIMIT_UPPER not in", values, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PARSED_LIMIT_UPPER between", value1, value2, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PARSED_LIMIT_UPPERNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAB_PARSED_LIMIT_UPPER not between", value1, value2, "LAB_PARSED_LIMIT_UPPER");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORIsNull() {
            addCriterion("LAB_PLUS_SIGN_INDICATOR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORIsNotNull() {
            addCriterion("LAB_PLUS_SIGN_INDICATOR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATOREqualTo(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR =", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORNotEqualTo(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR <>", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORGreaterThan(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR >", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR >=", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORLessThan(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR <", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORLessThanOrEqualTo(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR <=", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORLike(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR like", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORNotLike(String value) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR not like", value, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORIn(List<String> values) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR in", values, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORNotIn(List<String> values) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR not in", values, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORBetween(String value1, String value2) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR between", value1, value2, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PLUS_SIGN_INDICATORNotBetween(String value1, String value2) {
            addCriterion("LAB_PLUS_SIGN_INDICATOR not between", value1, value2, "LAB_PLUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORIsNull() {
            addCriterion("LAB_MINUS_SIGN_INDICATOR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORIsNotNull() {
            addCriterion("LAB_MINUS_SIGN_INDICATOR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATOREqualTo(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR =", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORNotEqualTo(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR <>", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORGreaterThan(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR >", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR >=", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORLessThan(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR <", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORLessThanOrEqualTo(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR <=", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORLike(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR like", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORNotLike(String value) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR not like", value, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORIn(List<String> values) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR in", values, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORNotIn(List<String> values) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR not in", values, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORBetween(String value1, String value2) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR between", value1, value2, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_MINUS_SIGN_INDICATORNotBetween(String value1, String value2) {
            addCriterion("LAB_MINUS_SIGN_INDICATOR not between", value1, value2, "LAB_MINUS_SIGN_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORIsNull() {
            addCriterion("LAB_PERCENT_INDICATOR is null");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORIsNotNull() {
            addCriterion("LAB_PERCENT_INDICATOR is not null");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATOREqualTo(String value) {
            addCriterion("LAB_PERCENT_INDICATOR =", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORNotEqualTo(String value) {
            addCriterion("LAB_PERCENT_INDICATOR <>", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORGreaterThan(String value) {
            addCriterion("LAB_PERCENT_INDICATOR >", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORGreaterThanOrEqualTo(String value) {
            addCriterion("LAB_PERCENT_INDICATOR >=", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORLessThan(String value) {
            addCriterion("LAB_PERCENT_INDICATOR <", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORLessThanOrEqualTo(String value) {
            addCriterion("LAB_PERCENT_INDICATOR <=", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORLike(String value) {
            addCriterion("LAB_PERCENT_INDICATOR like", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORNotLike(String value) {
            addCriterion("LAB_PERCENT_INDICATOR not like", value, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORIn(List<String> values) {
            addCriterion("LAB_PERCENT_INDICATOR in", values, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORNotIn(List<String> values) {
            addCriterion("LAB_PERCENT_INDICATOR not in", values, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORBetween(String value1, String value2) {
            addCriterion("LAB_PERCENT_INDICATOR between", value1, value2, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andLAB_PERCENT_INDICATORNotBetween(String value1, String value2) {
            addCriterion("LAB_PERCENT_INDICATOR not between", value1, value2, "LAB_PERCENT_INDICATOR");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.LAB_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}