package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

import java.math.BigDecimal;
import java.util.Date;

public class PatientLabResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.PT_ID_LAB
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer PT_ID_LAB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.DMP_ID_LAB
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String DMP_ID_LAB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_TEST_NAME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_TEST_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_SUBTEST_NAME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_SUBTEST_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_TEST_CATEGORY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_TEST_CATEGORY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_SUBTEST_CATEGORY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_SUBTEST_CATEGORY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PERFORMED_YEAR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Short LAB_PERFORMED_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.AGE_AT_LAB_PERFORMED_DATE_IN_DAYS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer AGE_AT_LAB_PERFORMED_DATE_IN_DAYS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PERFORMED_TIME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Date LAB_PERFORMED_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_ENTERED_YEAR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Short LAB_ENTERED_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.AGE_AT_LAB_ENTERED_DATE_IN_DAYS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer AGE_AT_LAB_ENTERED_DATE_IN_DAYS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_ENTERED_TIME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Date LAB_ENTERED_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_TEST_RESULT_NOTES
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_TEST_RESULT_NOTES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_TEST_RESULT_VALUE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_TEST_RESULT_VALUE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_UNIT_MEASURE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_UNIT_MEASURE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_ABNORMAL_FLAG
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_ABNORMAL_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_LIMIT_UPPER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_LIMIT_UPPER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_LIMIT_LOWER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_LIMIT_LOWER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PURE_NUMERIC_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_PURE_NUMERIC_INDICATOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PURE_NUMERIC_RESULT
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private BigDecimal LAB_PURE_NUMERIC_RESULT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_GREATER_THAN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_GREATER_THAN_INDICATOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_LESS_THAN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_LESS_THAN_INDICATOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PARSED_LIMIT_LOWER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private BigDecimal LAB_PARSED_LIMIT_LOWER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PARSED_NUMERIC_RESULT
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private BigDecimal LAB_PARSED_NUMERIC_RESULT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PARSED_LIMIT_UPPER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private BigDecimal LAB_PARSED_LIMIT_UPPER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PLUS_SIGN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_PLUS_SIGN_INDICATOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_MINUS_SIGN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_MINUS_SIGN_INDICATOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.LAB_V.LAB_PERCENT_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String LAB_PERCENT_INDICATOR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.PT_ID_LAB
     *
     * @return the value of DVCBIO.LAB_V.PT_ID_LAB
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getPT_ID_LAB() {
        return PT_ID_LAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.PT_ID_LAB
     *
     * @param PT_ID_LAB the value for DVCBIO.LAB_V.PT_ID_LAB
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setPT_ID_LAB(Integer PT_ID_LAB) {
        this.PT_ID_LAB = PT_ID_LAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.DMP_ID_LAB
     *
     * @return the value of DVCBIO.LAB_V.DMP_ID_LAB
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getDMP_ID_LAB() {
        return DMP_ID_LAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.DMP_ID_LAB
     *
     * @param DMP_ID_LAB the value for DVCBIO.LAB_V.DMP_ID_LAB
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDMP_ID_LAB(String DMP_ID_LAB) {
        this.DMP_ID_LAB = DMP_ID_LAB == null ? null : DMP_ID_LAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_TEST_NAME
     *
     * @return the value of DVCBIO.LAB_V.LAB_TEST_NAME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_TEST_NAME() {
        return LAB_TEST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_TEST_NAME
     *
     * @param LAB_TEST_NAME the value for DVCBIO.LAB_V.LAB_TEST_NAME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_TEST_NAME(String LAB_TEST_NAME) {
        this.LAB_TEST_NAME = LAB_TEST_NAME == null ? null : LAB_TEST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_SUBTEST_NAME
     *
     * @return the value of DVCBIO.LAB_V.LAB_SUBTEST_NAME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_SUBTEST_NAME() {
        return LAB_SUBTEST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_SUBTEST_NAME
     *
     * @param LAB_SUBTEST_NAME the value for DVCBIO.LAB_V.LAB_SUBTEST_NAME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_SUBTEST_NAME(String LAB_SUBTEST_NAME) {
        this.LAB_SUBTEST_NAME = LAB_SUBTEST_NAME == null ? null : LAB_SUBTEST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_TEST_CATEGORY
     *
     * @return the value of DVCBIO.LAB_V.LAB_TEST_CATEGORY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_TEST_CATEGORY() {
        return LAB_TEST_CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_TEST_CATEGORY
     *
     * @param LAB_TEST_CATEGORY the value for DVCBIO.LAB_V.LAB_TEST_CATEGORY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_TEST_CATEGORY(String LAB_TEST_CATEGORY) {
        this.LAB_TEST_CATEGORY = LAB_TEST_CATEGORY == null ? null : LAB_TEST_CATEGORY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_SUBTEST_CATEGORY
     *
     * @return the value of DVCBIO.LAB_V.LAB_SUBTEST_CATEGORY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_SUBTEST_CATEGORY() {
        return LAB_SUBTEST_CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_SUBTEST_CATEGORY
     *
     * @param LAB_SUBTEST_CATEGORY the value for DVCBIO.LAB_V.LAB_SUBTEST_CATEGORY
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_SUBTEST_CATEGORY(String LAB_SUBTEST_CATEGORY) {
        this.LAB_SUBTEST_CATEGORY = LAB_SUBTEST_CATEGORY == null ? null : LAB_SUBTEST_CATEGORY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PERFORMED_YEAR
     *
     * @return the value of DVCBIO.LAB_V.LAB_PERFORMED_YEAR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Short getLAB_PERFORMED_YEAR() {
        return LAB_PERFORMED_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PERFORMED_YEAR
     *
     * @param LAB_PERFORMED_YEAR the value for DVCBIO.LAB_V.LAB_PERFORMED_YEAR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PERFORMED_YEAR(Short LAB_PERFORMED_YEAR) {
        this.LAB_PERFORMED_YEAR = LAB_PERFORMED_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.AGE_AT_LAB_PERFORMED_DATE_IN_DAYS
     *
     * @return the value of DVCBIO.LAB_V.AGE_AT_LAB_PERFORMED_DATE_IN_DAYS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getAGE_AT_LAB_PERFORMED_DATE_IN_DAYS() {
        return AGE_AT_LAB_PERFORMED_DATE_IN_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.AGE_AT_LAB_PERFORMED_DATE_IN_DAYS
     *
     * @param AGE_AT_LAB_PERFORMED_DATE_IN_DAYS the value for DVCBIO.LAB_V.AGE_AT_LAB_PERFORMED_DATE_IN_DAYS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setAGE_AT_LAB_PERFORMED_DATE_IN_DAYS(Integer AGE_AT_LAB_PERFORMED_DATE_IN_DAYS) {
        this.AGE_AT_LAB_PERFORMED_DATE_IN_DAYS = AGE_AT_LAB_PERFORMED_DATE_IN_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PERFORMED_TIME
     *
     * @return the value of DVCBIO.LAB_V.LAB_PERFORMED_TIME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Date getLAB_PERFORMED_TIME() {
        return LAB_PERFORMED_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PERFORMED_TIME
     *
     * @param LAB_PERFORMED_TIME the value for DVCBIO.LAB_V.LAB_PERFORMED_TIME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PERFORMED_TIME(Date LAB_PERFORMED_TIME) {
        this.LAB_PERFORMED_TIME = LAB_PERFORMED_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_ENTERED_YEAR
     *
     * @return the value of DVCBIO.LAB_V.LAB_ENTERED_YEAR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Short getLAB_ENTERED_YEAR() {
        return LAB_ENTERED_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_ENTERED_YEAR
     *
     * @param LAB_ENTERED_YEAR the value for DVCBIO.LAB_V.LAB_ENTERED_YEAR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_ENTERED_YEAR(Short LAB_ENTERED_YEAR) {
        this.LAB_ENTERED_YEAR = LAB_ENTERED_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.AGE_AT_LAB_ENTERED_DATE_IN_DAYS
     *
     * @return the value of DVCBIO.LAB_V.AGE_AT_LAB_ENTERED_DATE_IN_DAYS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getAGE_AT_LAB_ENTERED_DATE_IN_DAYS() {
        return AGE_AT_LAB_ENTERED_DATE_IN_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.AGE_AT_LAB_ENTERED_DATE_IN_DAYS
     *
     * @param AGE_AT_LAB_ENTERED_DATE_IN_DAYS the value for DVCBIO.LAB_V.AGE_AT_LAB_ENTERED_DATE_IN_DAYS
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setAGE_AT_LAB_ENTERED_DATE_IN_DAYS(Integer AGE_AT_LAB_ENTERED_DATE_IN_DAYS) {
        this.AGE_AT_LAB_ENTERED_DATE_IN_DAYS = AGE_AT_LAB_ENTERED_DATE_IN_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_ENTERED_TIME
     *
     * @return the value of DVCBIO.LAB_V.LAB_ENTERED_TIME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Date getLAB_ENTERED_TIME() {
        return LAB_ENTERED_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_ENTERED_TIME
     *
     * @param LAB_ENTERED_TIME the value for DVCBIO.LAB_V.LAB_ENTERED_TIME
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_ENTERED_TIME(Date LAB_ENTERED_TIME) {
        this.LAB_ENTERED_TIME = LAB_ENTERED_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_TEST_RESULT_NOTES
     *
     * @return the value of DVCBIO.LAB_V.LAB_TEST_RESULT_NOTES
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_TEST_RESULT_NOTES() {
        return LAB_TEST_RESULT_NOTES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_TEST_RESULT_NOTES
     *
     * @param LAB_TEST_RESULT_NOTES the value for DVCBIO.LAB_V.LAB_TEST_RESULT_NOTES
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_TEST_RESULT_NOTES(String LAB_TEST_RESULT_NOTES) {
        this.LAB_TEST_RESULT_NOTES = LAB_TEST_RESULT_NOTES == null ? null : LAB_TEST_RESULT_NOTES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_TEST_RESULT_VALUE
     *
     * @return the value of DVCBIO.LAB_V.LAB_TEST_RESULT_VALUE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_TEST_RESULT_VALUE() {
        return LAB_TEST_RESULT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_TEST_RESULT_VALUE
     *
     * @param LAB_TEST_RESULT_VALUE the value for DVCBIO.LAB_V.LAB_TEST_RESULT_VALUE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_TEST_RESULT_VALUE(String LAB_TEST_RESULT_VALUE) {
        this.LAB_TEST_RESULT_VALUE = LAB_TEST_RESULT_VALUE == null ? null : LAB_TEST_RESULT_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_UNIT_MEASURE
     *
     * @return the value of DVCBIO.LAB_V.LAB_UNIT_MEASURE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_UNIT_MEASURE() {
        return LAB_UNIT_MEASURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_UNIT_MEASURE
     *
     * @param LAB_UNIT_MEASURE the value for DVCBIO.LAB_V.LAB_UNIT_MEASURE
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_UNIT_MEASURE(String LAB_UNIT_MEASURE) {
        this.LAB_UNIT_MEASURE = LAB_UNIT_MEASURE == null ? null : LAB_UNIT_MEASURE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_ABNORMAL_FLAG
     *
     * @return the value of DVCBIO.LAB_V.LAB_ABNORMAL_FLAG
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_ABNORMAL_FLAG() {
        return LAB_ABNORMAL_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_ABNORMAL_FLAG
     *
     * @param LAB_ABNORMAL_FLAG the value for DVCBIO.LAB_V.LAB_ABNORMAL_FLAG
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_ABNORMAL_FLAG(String LAB_ABNORMAL_FLAG) {
        this.LAB_ABNORMAL_FLAG = LAB_ABNORMAL_FLAG == null ? null : LAB_ABNORMAL_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_LIMIT_UPPER
     *
     * @return the value of DVCBIO.LAB_V.LAB_LIMIT_UPPER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_LIMIT_UPPER() {
        return LAB_LIMIT_UPPER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_LIMIT_UPPER
     *
     * @param LAB_LIMIT_UPPER the value for DVCBIO.LAB_V.LAB_LIMIT_UPPER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_LIMIT_UPPER(String LAB_LIMIT_UPPER) {
        this.LAB_LIMIT_UPPER = LAB_LIMIT_UPPER == null ? null : LAB_LIMIT_UPPER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_LIMIT_LOWER
     *
     * @return the value of DVCBIO.LAB_V.LAB_LIMIT_LOWER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_LIMIT_LOWER() {
        return LAB_LIMIT_LOWER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_LIMIT_LOWER
     *
     * @param LAB_LIMIT_LOWER the value for DVCBIO.LAB_V.LAB_LIMIT_LOWER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_LIMIT_LOWER(String LAB_LIMIT_LOWER) {
        this.LAB_LIMIT_LOWER = LAB_LIMIT_LOWER == null ? null : LAB_LIMIT_LOWER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PURE_NUMERIC_INDICATOR
     *
     * @return the value of DVCBIO.LAB_V.LAB_PURE_NUMERIC_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_PURE_NUMERIC_INDICATOR() {
        return LAB_PURE_NUMERIC_INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PURE_NUMERIC_INDICATOR
     *
     * @param LAB_PURE_NUMERIC_INDICATOR the value for DVCBIO.LAB_V.LAB_PURE_NUMERIC_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PURE_NUMERIC_INDICATOR(String LAB_PURE_NUMERIC_INDICATOR) {
        this.LAB_PURE_NUMERIC_INDICATOR = LAB_PURE_NUMERIC_INDICATOR == null ? null : LAB_PURE_NUMERIC_INDICATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PURE_NUMERIC_RESULT
     *
     * @return the value of DVCBIO.LAB_V.LAB_PURE_NUMERIC_RESULT
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public BigDecimal getLAB_PURE_NUMERIC_RESULT() {
        return LAB_PURE_NUMERIC_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PURE_NUMERIC_RESULT
     *
     * @param LAB_PURE_NUMERIC_RESULT the value for DVCBIO.LAB_V.LAB_PURE_NUMERIC_RESULT
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PURE_NUMERIC_RESULT(BigDecimal LAB_PURE_NUMERIC_RESULT) {
        this.LAB_PURE_NUMERIC_RESULT = LAB_PURE_NUMERIC_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_GREATER_THAN_INDICATOR
     *
     * @return the value of DVCBIO.LAB_V.LAB_GREATER_THAN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_GREATER_THAN_INDICATOR() {
        return LAB_GREATER_THAN_INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_GREATER_THAN_INDICATOR
     *
     * @param LAB_GREATER_THAN_INDICATOR the value for DVCBIO.LAB_V.LAB_GREATER_THAN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_GREATER_THAN_INDICATOR(String LAB_GREATER_THAN_INDICATOR) {
        this.LAB_GREATER_THAN_INDICATOR = LAB_GREATER_THAN_INDICATOR == null ? null : LAB_GREATER_THAN_INDICATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_LESS_THAN_INDICATOR
     *
     * @return the value of DVCBIO.LAB_V.LAB_LESS_THAN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_LESS_THAN_INDICATOR() {
        return LAB_LESS_THAN_INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_LESS_THAN_INDICATOR
     *
     * @param LAB_LESS_THAN_INDICATOR the value for DVCBIO.LAB_V.LAB_LESS_THAN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_LESS_THAN_INDICATOR(String LAB_LESS_THAN_INDICATOR) {
        this.LAB_LESS_THAN_INDICATOR = LAB_LESS_THAN_INDICATOR == null ? null : LAB_LESS_THAN_INDICATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PARSED_LIMIT_LOWER
     *
     * @return the value of DVCBIO.LAB_V.LAB_PARSED_LIMIT_LOWER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public BigDecimal getLAB_PARSED_LIMIT_LOWER() {
        return LAB_PARSED_LIMIT_LOWER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PARSED_LIMIT_LOWER
     *
     * @param LAB_PARSED_LIMIT_LOWER the value for DVCBIO.LAB_V.LAB_PARSED_LIMIT_LOWER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PARSED_LIMIT_LOWER(BigDecimal LAB_PARSED_LIMIT_LOWER) {
        this.LAB_PARSED_LIMIT_LOWER = LAB_PARSED_LIMIT_LOWER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PARSED_NUMERIC_RESULT
     *
     * @return the value of DVCBIO.LAB_V.LAB_PARSED_NUMERIC_RESULT
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public BigDecimal getLAB_PARSED_NUMERIC_RESULT() {
        return LAB_PARSED_NUMERIC_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PARSED_NUMERIC_RESULT
     *
     * @param LAB_PARSED_NUMERIC_RESULT the value for DVCBIO.LAB_V.LAB_PARSED_NUMERIC_RESULT
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PARSED_NUMERIC_RESULT(BigDecimal LAB_PARSED_NUMERIC_RESULT) {
        this.LAB_PARSED_NUMERIC_RESULT = LAB_PARSED_NUMERIC_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PARSED_LIMIT_UPPER
     *
     * @return the value of DVCBIO.LAB_V.LAB_PARSED_LIMIT_UPPER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public BigDecimal getLAB_PARSED_LIMIT_UPPER() {
        return LAB_PARSED_LIMIT_UPPER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PARSED_LIMIT_UPPER
     *
     * @param LAB_PARSED_LIMIT_UPPER the value for DVCBIO.LAB_V.LAB_PARSED_LIMIT_UPPER
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PARSED_LIMIT_UPPER(BigDecimal LAB_PARSED_LIMIT_UPPER) {
        this.LAB_PARSED_LIMIT_UPPER = LAB_PARSED_LIMIT_UPPER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PLUS_SIGN_INDICATOR
     *
     * @return the value of DVCBIO.LAB_V.LAB_PLUS_SIGN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_PLUS_SIGN_INDICATOR() {
        return LAB_PLUS_SIGN_INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PLUS_SIGN_INDICATOR
     *
     * @param LAB_PLUS_SIGN_INDICATOR the value for DVCBIO.LAB_V.LAB_PLUS_SIGN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PLUS_SIGN_INDICATOR(String LAB_PLUS_SIGN_INDICATOR) {
        this.LAB_PLUS_SIGN_INDICATOR = LAB_PLUS_SIGN_INDICATOR == null ? null : LAB_PLUS_SIGN_INDICATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_MINUS_SIGN_INDICATOR
     *
     * @return the value of DVCBIO.LAB_V.LAB_MINUS_SIGN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_MINUS_SIGN_INDICATOR() {
        return LAB_MINUS_SIGN_INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_MINUS_SIGN_INDICATOR
     *
     * @param LAB_MINUS_SIGN_INDICATOR the value for DVCBIO.LAB_V.LAB_MINUS_SIGN_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_MINUS_SIGN_INDICATOR(String LAB_MINUS_SIGN_INDICATOR) {
        this.LAB_MINUS_SIGN_INDICATOR = LAB_MINUS_SIGN_INDICATOR == null ? null : LAB_MINUS_SIGN_INDICATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.LAB_V.LAB_PERCENT_INDICATOR
     *
     * @return the value of DVCBIO.LAB_V.LAB_PERCENT_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getLAB_PERCENT_INDICATOR() {
        return LAB_PERCENT_INDICATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.LAB_V.LAB_PERCENT_INDICATOR
     *
     * @param LAB_PERCENT_INDICATOR the value for DVCBIO.LAB_V.LAB_PERCENT_INDICATOR
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setLAB_PERCENT_INDICATOR(String LAB_PERCENT_INDICATOR) {
        this.LAB_PERCENT_INDICATOR = LAB_PERCENT_INDICATOR == null ? null : LAB_PERCENT_INDICATOR.trim();
    }
}