package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

public class PatientDmpPathologyReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATHOLOGY_DMP_V.PT_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer PT_ID_PATH_DMP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATHOLOGY_DMP_V.RPT_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private Integer RPT_ID_PATH_DMP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATHOLOGY_DMP_V.DMP_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String DMP_ID_PATH_DMP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DVCBIO.PATHOLOGY_DMP_V.SAMPLE_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    private String SAMPLE_ID_PATH_DMP;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATHOLOGY_DMP_V.PT_ID_PATH_DMP
     *
     * @return the value of DVCBIO.PATHOLOGY_DMP_V.PT_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getPT_ID_PATH_DMP() {
        return PT_ID_PATH_DMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATHOLOGY_DMP_V.PT_ID_PATH_DMP
     *
     * @param PT_ID_PATH_DMP the value for DVCBIO.PATHOLOGY_DMP_V.PT_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setPT_ID_PATH_DMP(Integer PT_ID_PATH_DMP) {
        this.PT_ID_PATH_DMP = PT_ID_PATH_DMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATHOLOGY_DMP_V.RPT_ID_PATH_DMP
     *
     * @return the value of DVCBIO.PATHOLOGY_DMP_V.RPT_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Integer getRPT_ID_PATH_DMP() {
        return RPT_ID_PATH_DMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATHOLOGY_DMP_V.RPT_ID_PATH_DMP
     *
     * @param RPT_ID_PATH_DMP the value for DVCBIO.PATHOLOGY_DMP_V.RPT_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setRPT_ID_PATH_DMP(Integer RPT_ID_PATH_DMP) {
        this.RPT_ID_PATH_DMP = RPT_ID_PATH_DMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATHOLOGY_DMP_V.DMP_ID_PATH_DMP
     *
     * @return the value of DVCBIO.PATHOLOGY_DMP_V.DMP_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getDMP_ID_PATH_DMP() {
        return DMP_ID_PATH_DMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATHOLOGY_DMP_V.DMP_ID_PATH_DMP
     *
     * @param DMP_ID_PATH_DMP the value for DVCBIO.PATHOLOGY_DMP_V.DMP_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDMP_ID_PATH_DMP(String DMP_ID_PATH_DMP) {
        this.DMP_ID_PATH_DMP = DMP_ID_PATH_DMP == null ? null : DMP_ID_PATH_DMP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DVCBIO.PATHOLOGY_DMP_V.SAMPLE_ID_PATH_DMP
     *
     * @return the value of DVCBIO.PATHOLOGY_DMP_V.SAMPLE_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getSAMPLE_ID_PATH_DMP() {
        return SAMPLE_ID_PATH_DMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DVCBIO.PATHOLOGY_DMP_V.SAMPLE_ID_PATH_DMP
     *
     * @param SAMPLE_ID_PATH_DMP the value for DVCBIO.PATHOLOGY_DMP_V.SAMPLE_ID_PATH_DMP
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setSAMPLE_ID_PATH_DMP(String SAMPLE_ID_PATH_DMP) {
        this.SAMPLE_ID_PATH_DMP = SAMPLE_ID_PATH_DMP == null ? null : SAMPLE_ID_PATH_DMP.trim();
    }
}