package org.mskcc.cbio.clinicaldata.darwin.model.dvcbio;

import java.util.ArrayList;
import java.util.List;

public class PatientIcd9RecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public PatientIcd9RecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPT_ID_ICD9IsNull() {
            addCriterion("PT_ID_ICD9 is null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9IsNotNull() {
            addCriterion("PT_ID_ICD9 is not null");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9EqualTo(Integer value) {
            addCriterion("PT_ID_ICD9 =", value, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9NotEqualTo(Integer value) {
            addCriterion("PT_ID_ICD9 <>", value, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9GreaterThan(Integer value) {
            addCriterion("PT_ID_ICD9 >", value, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9GreaterThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_ICD9 >=", value, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9LessThan(Integer value) {
            addCriterion("PT_ID_ICD9 <", value, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9LessThanOrEqualTo(Integer value) {
            addCriterion("PT_ID_ICD9 <=", value, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9In(List<Integer> values) {
            addCriterion("PT_ID_ICD9 in", values, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9NotIn(List<Integer> values) {
            addCriterion("PT_ID_ICD9 not in", values, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9Between(Integer value1, Integer value2) {
            addCriterion("PT_ID_ICD9 between", value1, value2, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andPT_ID_ICD9NotBetween(Integer value1, Integer value2) {
            addCriterion("PT_ID_ICD9 not between", value1, value2, "PT_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9IsNull() {
            addCriterion("DMP_ID_ICD9 is null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9IsNotNull() {
            addCriterion("DMP_ID_ICD9 is not null");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9EqualTo(String value) {
            addCriterion("DMP_ID_ICD9 =", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9NotEqualTo(String value) {
            addCriterion("DMP_ID_ICD9 <>", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9GreaterThan(String value) {
            addCriterion("DMP_ID_ICD9 >", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9GreaterThanOrEqualTo(String value) {
            addCriterion("DMP_ID_ICD9 >=", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9LessThan(String value) {
            addCriterion("DMP_ID_ICD9 <", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9LessThanOrEqualTo(String value) {
            addCriterion("DMP_ID_ICD9 <=", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9Like(String value) {
            addCriterion("DMP_ID_ICD9 like", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9NotLike(String value) {
            addCriterion("DMP_ID_ICD9 not like", value, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9In(List<String> values) {
            addCriterion("DMP_ID_ICD9 in", values, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9NotIn(List<String> values) {
            addCriterion("DMP_ID_ICD9 not in", values, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9Between(String value1, String value2) {
            addCriterion("DMP_ID_ICD9 between", value1, value2, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andDMP_ID_ICD9NotBetween(String value1, String value2) {
            addCriterion("DMP_ID_ICD9 not between", value1, value2, "DMP_ID_ICD9");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODEIsNull() {
            addCriterion("ICD_9_CODE is null");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODEIsNotNull() {
            addCriterion("ICD_9_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODEEqualTo(String value) {
            addCriterion("ICD_9_CODE =", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODENotEqualTo(String value) {
            addCriterion("ICD_9_CODE <>", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODEGreaterThan(String value) {
            addCriterion("ICD_9_CODE >", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODEGreaterThanOrEqualTo(String value) {
            addCriterion("ICD_9_CODE >=", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODELessThan(String value) {
            addCriterion("ICD_9_CODE <", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODELessThanOrEqualTo(String value) {
            addCriterion("ICD_9_CODE <=", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODELike(String value) {
            addCriterion("ICD_9_CODE like", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODENotLike(String value) {
            addCriterion("ICD_9_CODE not like", value, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODEIn(List<String> values) {
            addCriterion("ICD_9_CODE in", values, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODENotIn(List<String> values) {
            addCriterion("ICD_9_CODE not in", values, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODEBetween(String value1, String value2) {
            addCriterion("ICD_9_CODE between", value1, value2, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_CODENotBetween(String value1, String value2) {
            addCriterion("ICD_9_CODE not between", value1, value2, "ICD_9_CODE");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONIsNull() {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONIsNotNull() {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONEqualTo(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION =", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONNotEqualTo(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION <>", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONGreaterThan(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION >", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONGreaterThanOrEqualTo(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION >=", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONLessThan(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION <", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONLessThanOrEqualTo(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION <=", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONLike(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION like", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONNotLike(String value) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION not like", value, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONIn(List<String> values) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION in", values, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONNotIn(List<String> values) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION not in", values, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONBetween(String value1, String value2) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION between", value1, value2, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_MSK_CODE_DESCRIPTIONNotBetween(String value1, String value2) {
            addCriterion("ICD_9_MSK_CODE_DESCRIPTION not between", value1, value2, "ICD_9_MSK_CODE_DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARIsNull() {
            addCriterion("ICD_9_DIAGNOSIS_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARIsNotNull() {
            addCriterion("ICD_9_DIAGNOSIS_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEAREqualTo(Short value) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR =", value, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARNotEqualTo(Short value) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR <>", value, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARGreaterThan(Short value) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR >", value, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARGreaterThanOrEqualTo(Short value) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR >=", value, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARLessThan(Short value) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR <", value, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARLessThanOrEqualTo(Short value) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR <=", value, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARIn(List<Short> values) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR in", values, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARNotIn(List<Short> values) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR not in", values, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARBetween(Short value1, Short value2) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR between", value1, value2, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_YEARNotBetween(Short value1, Short value2) {
            addCriterion("ICD_9_DIAGNOSIS_YEAR not between", value1, value2, "ICD_9_DIAGNOSIS_YEAR");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSIsNull() {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSIsNotNull() {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSEqualTo(Integer value) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS =", value, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSNotEqualTo(Integer value) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS <>", value, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSGreaterThan(Integer value) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS >", value, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS >=", value, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSLessThan(Integer value) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS <", value, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSLessThanOrEqualTo(Integer value) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS <=", value, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSIn(List<Integer> values) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS in", values, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSNotIn(List<Integer> values) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS not in", values, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS between", value1, value2, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andAGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYSNotBetween(Integer value1, Integer value2) {
            addCriterion("AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS not between", value1, value2, "AGE_AT_ICD_9_DIAGNOSIS_DATE_IN_DAYS");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPEIsNull() {
            addCriterion("ICD_9_DIAGNOSIS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPEIsNotNull() {
            addCriterion("ICD_9_DIAGNOSIS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPEEqualTo(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE =", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPENotEqualTo(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE <>", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPEGreaterThan(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE >", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE >=", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPELessThan(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE <", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPELessThanOrEqualTo(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE <=", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPELike(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE like", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPENotLike(String value) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE not like", value, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPEIn(List<String> values) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE in", values, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPENotIn(List<String> values) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE not in", values, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPEBetween(String value1, String value2) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE between", value1, value2, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DIAGNOSIS_TYPENotBetween(String value1, String value2) {
            addCriterion("ICD_9_DIAGNOSIS_TYPE not between", value1, value2, "ICD_9_DIAGNOSIS_TYPE");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPIsNull() {
            addCriterion("ICD_9_DX_IP_OP is null");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPIsNotNull() {
            addCriterion("ICD_9_DX_IP_OP is not null");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPEqualTo(String value) {
            addCriterion("ICD_9_DX_IP_OP =", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPNotEqualTo(String value) {
            addCriterion("ICD_9_DX_IP_OP <>", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPGreaterThan(String value) {
            addCriterion("ICD_9_DX_IP_OP >", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPGreaterThanOrEqualTo(String value) {
            addCriterion("ICD_9_DX_IP_OP >=", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPLessThan(String value) {
            addCriterion("ICD_9_DX_IP_OP <", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPLessThanOrEqualTo(String value) {
            addCriterion("ICD_9_DX_IP_OP <=", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPLike(String value) {
            addCriterion("ICD_9_DX_IP_OP like", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPNotLike(String value) {
            addCriterion("ICD_9_DX_IP_OP not like", value, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPIn(List<String> values) {
            addCriterion("ICD_9_DX_IP_OP in", values, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPNotIn(List<String> values) {
            addCriterion("ICD_9_DX_IP_OP not in", values, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPBetween(String value1, String value2) {
            addCriterion("ICD_9_DX_IP_OP between", value1, value2, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_DX_IP_OPNotBetween(String value1, String value2) {
            addCriterion("ICD_9_DX_IP_OP not between", value1, value2, "ICD_9_DX_IP_OP");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORIsNull() {
            addCriterion("ICD_9_CIC_CODED_INDICATOR is null");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORIsNotNull() {
            addCriterion("ICD_9_CIC_CODED_INDICATOR is not null");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATOREqualTo(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR =", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORNotEqualTo(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR <>", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORGreaterThan(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR >", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORGreaterThanOrEqualTo(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR >=", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORLessThan(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR <", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORLessThanOrEqualTo(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR <=", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORLike(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR like", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORNotLike(String value) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR not like", value, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORIn(List<String> values) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR in", values, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORNotIn(List<String> values) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR not in", values, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORBetween(String value1, String value2) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR between", value1, value2, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD_9_CIC_CODED_INDICATORNotBetween(String value1, String value2) {
            addCriterion("ICD_9_CIC_CODED_INDICATOR not between", value1, value2, "ICD_9_CIC_CODED_INDICATOR");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDIsNull() {
            addCriterion("ICD9_METS_IND is null");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDIsNotNull() {
            addCriterion("ICD9_METS_IND is not null");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDEqualTo(String value) {
            addCriterion("ICD9_METS_IND =", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotEqualTo(String value) {
            addCriterion("ICD9_METS_IND <>", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDGreaterThan(String value) {
            addCriterion("ICD9_METS_IND >", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDGreaterThanOrEqualTo(String value) {
            addCriterion("ICD9_METS_IND >=", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDLessThan(String value) {
            addCriterion("ICD9_METS_IND <", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDLessThanOrEqualTo(String value) {
            addCriterion("ICD9_METS_IND <=", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDLike(String value) {
            addCriterion("ICD9_METS_IND like", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotLike(String value) {
            addCriterion("ICD9_METS_IND not like", value, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDIn(List<String> values) {
            addCriterion("ICD9_METS_IND in", values, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotIn(List<String> values) {
            addCriterion("ICD9_METS_IND not in", values, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDBetween(String value1, String value2) {
            addCriterion("ICD9_METS_IND between", value1, value2, "ICD9_METS_IND");
            return (Criteria) this;
        }

        public Criteria andICD9_METS_INDNotBetween(String value1, String value2) {
            addCriterion("ICD9_METS_IND not between", value1, value2, "ICD9_METS_IND");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DVCBIO.ICD9_V
     *
     * @mbggenerated Fri Sep 04 16:58:24 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}