package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalAttribute;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalAttributeExample;

public interface CbioClinicalAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioClinicalAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioClinicalAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByPrimaryKey(String ATTR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioClinicalAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioClinicalAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioClinicalAttribute> selectByExample(CbioClinicalAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    CbioClinicalAttribute selectByPrimaryKey(String ATTR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioClinicalAttribute record, @Param("example") CbioClinicalAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioClinicalAttribute record, @Param("example") CbioClinicalAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKeySelective(CbioClinicalAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_attribute
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKey(CbioClinicalAttribute record);
}