package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioCancerStudy;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioCancerStudyExample;

public interface CbioCancerStudyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioCancerStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioCancerStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByPrimaryKey(Integer CANCER_STUDY_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioCancerStudy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioCancerStudy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioCancerStudy> selectByExample(CbioCancerStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    CbioCancerStudy selectByPrimaryKey(Integer CANCER_STUDY_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioCancerStudy record, @Param("example") CbioCancerStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioCancerStudy record, @Param("example") CbioCancerStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKeySelective(CbioCancerStudy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancer_study
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKey(CbioCancerStudy record);
}