package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalPatient;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalPatientExample;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalPatientKey;

public interface CbioClinicalPatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioClinicalPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioClinicalPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByPrimaryKey(CbioClinicalPatientKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioClinicalPatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioClinicalPatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioClinicalPatient> selectByExample(CbioClinicalPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    CbioClinicalPatient selectByPrimaryKey(CbioClinicalPatientKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioClinicalPatient record, @Param("example") CbioClinicalPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioClinicalPatient record, @Param("example") CbioClinicalPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKeySelective(CbioClinicalPatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_patient
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKey(CbioClinicalPatient record);
}