package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioMutation;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioMutationExample;

public interface CbioMutationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutation
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioMutationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutation
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioMutationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutation
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioMutation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutation
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioMutation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutation
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioMutation> selectByExample(CbioMutationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutation
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioMutation record, @Param("example") CbioMutationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutation
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioMutation record, @Param("example") CbioMutationExample example);
}