package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalEvent;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalEventExample;

public interface CbioClinicalEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioClinicalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioClinicalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByPrimaryKey(Integer CLINICAL_EVENT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioClinicalEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioClinicalEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioClinicalEvent> selectByExample(CbioClinicalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    CbioClinicalEvent selectByPrimaryKey(Integer CLINICAL_EVENT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioClinicalEvent record, @Param("example") CbioClinicalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioClinicalEvent record, @Param("example") CbioClinicalEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKeySelective(CbioClinicalEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKey(CbioClinicalEvent record);
}