package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalEventData;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioClinicalEventDataExample;

public interface CbioClinicalEventDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event_data
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioClinicalEventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event_data
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioClinicalEventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event_data
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioClinicalEventData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event_data
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioClinicalEventData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event_data
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioClinicalEventData> selectByExample(CbioClinicalEventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event_data
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioClinicalEventData record, @Param("example") CbioClinicalEventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clinical_event_data
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioClinicalEventData record, @Param("example") CbioClinicalEventDataExample example);
}