package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioSample;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioSampleExample;

public interface CbioSampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByPrimaryKey(Integer INTERNAL_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioSample> selectByExample(CbioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    CbioSample selectByPrimaryKey(Integer INTERNAL_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioSample record, @Param("example") CbioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioSample record, @Param("example") CbioSampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKeySelective(CbioSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKey(CbioSample record);
}