package org.mskcc.cbio.clinicaldata.cbiodata.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioTypeOfCancer;
import org.mskcc.cbio.clinicaldata.cbiodata.model.CbioTypeOfCancerExample;

public interface CbioTypeOfCancerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int countByExample(CbioTypeOfCancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByExample(CbioTypeOfCancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int deleteByPrimaryKey(String TYPE_OF_CANCER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insert(CbioTypeOfCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int insertSelective(CbioTypeOfCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    List<CbioTypeOfCancer> selectByExample(CbioTypeOfCancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    CbioTypeOfCancer selectByPrimaryKey(String TYPE_OF_CANCER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CbioTypeOfCancer record, @Param("example") CbioTypeOfCancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByExample(@Param("record") CbioTypeOfCancer record, @Param("example") CbioTypeOfCancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKeySelective(CbioTypeOfCancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_of_cancer
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    int updateByPrimaryKey(CbioTypeOfCancer record);
}