package org.mskcc.cbio.clinicaldata.crdb.rdbms.dao.cbioint;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.crdb.rdbms.model.cbioint.CrdbImpactSurvey;
import org.mskcc.cbio.clinicaldata.crdb.rdbms.model.cbioint.CrdbImpactSurveyExample;

import java.util.List;

public interface CrdbImpactSurveyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_IMPACT_SURVEY_12_245
     *
     *
     */
    int countByExample(CrdbImpactSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_IMPACT_SURVEY_12_245
     *
     *
     */
    int deleteByExample(CrdbImpactSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_IMPACT_SURVEY_12_245
     *
     *
     */
    int insert(CrdbImpactSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_IMPACT_SURVEY_12_245
     *
     *
     */
    int insertSelective(CrdbImpactSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_IMPACT_SURVEY_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    List<CrdbImpactSurvey> selectByExample(CrdbImpactSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_IMPACT_SURVEY_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CrdbImpactSurvey record, @Param("example") CrdbImpactSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_IMPACT_SURVEY_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int updateByExample(@Param("record") CrdbImpactSurvey record, @Param("example") CrdbImpactSurveyExample example);
}