package org.mskcc.cbio.clinicaldata.crdb.rdbms.dao.cbioint;

import org.apache.ibatis.annotations.Param;
import org.mskcc.cbio.clinicaldata.crdb.rdbms.model.cbioint.CrdbDataset;
import org.mskcc.cbio.clinicaldata.crdb.rdbms.model.cbioint.CrdbDatasetExample;

import java.util.List;

public interface CrdbDatasetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_MIN_DATASET_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int countByExample(CrdbDatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_MIN_DATASET_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int deleteByExample(CrdbDatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_MIN_DATASET_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int insert(CrdbDataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_MIN_DATASET_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int insertSelective(CrdbDataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_MIN_DATASET_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    List<CrdbDataset> selectByExample(CrdbDatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_MIN_DATASET_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int updateByExampleSelective(@Param("record") CrdbDataset record, @Param("example") CrdbDatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CBIOINT.V_MIN_DATASET_12_245
     *
     * @mbggenerated Fri Mar 27 11:05:53 EDT 2015
     */
    int updateByExample(@Param("record") CrdbDataset record, @Param("example") CrdbDatasetExample example);
}