package org.mskcc.cbio.clinicaldata.cbiodata.model;

public class CbioMutation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.MUTATION_EVENT_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer MUTATION_EVENT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.GENETIC_PROFILE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer GENETIC_PROFILE_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.SAMPLE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer SAMPLE_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.ENTREZ_GENE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer ENTREZ_GENE_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.CENTER
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String CENTER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.SEQUENCER
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String SEQUENCER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.MUTATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String MUTATION_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.VALIDATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String VALIDATION_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.TUMOR_SEQ_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String TUMOR_SEQ_ALLELE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.TUMOR_SEQ_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String TUMOR_SEQ_ALLELE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.MATCHED_NORM_SAMPLE_BARCODE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String MATCHED_NORM_SAMPLE_BARCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.MATCH_NORM_SEQ_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String MATCH_NORM_SEQ_ALLELE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.MATCH_NORM_SEQ_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String MATCH_NORM_SEQ_ALLELE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.TUMOR_VALIDATION_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String TUMOR_VALIDATION_ALLELE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.TUMOR_VALIDATION_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String TUMOR_VALIDATION_ALLELE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.MATCH_NORM_VALIDATION_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String MATCH_NORM_VALIDATION_ALLELE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.MATCH_NORM_VALIDATION_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String MATCH_NORM_VALIDATION_ALLELE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.VERIFICATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String VERIFICATION_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.SEQUENCING_PHASE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String SEQUENCING_PHASE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.SEQUENCE_SOURCE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String SEQUENCE_SOURCE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.VALIDATION_METHOD
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String VALIDATION_METHOD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.SCORE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String SCORE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.BAM_FILE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String BAM_FILE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.TUMOR_ALT_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer TUMOR_ALT_COUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.TUMOR_REF_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer TUMOR_REF_COUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.NORMAL_ALT_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer NORMAL_ALT_COUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mutation.NORMAL_REF_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Integer NORMAL_REF_COUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.MUTATION_EVENT_ID
     *
     * @return the value of mutation.MUTATION_EVENT_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getMUTATION_EVENT_ID() {
        return MUTATION_EVENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.MUTATION_EVENT_ID
     *
     * @param MUTATION_EVENT_ID the value for mutation.MUTATION_EVENT_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setMUTATION_EVENT_ID(Integer MUTATION_EVENT_ID) {
        this.MUTATION_EVENT_ID = MUTATION_EVENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.GENETIC_PROFILE_ID
     *
     * @return the value of mutation.GENETIC_PROFILE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getGENETIC_PROFILE_ID() {
        return GENETIC_PROFILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.GENETIC_PROFILE_ID
     *
     * @param GENETIC_PROFILE_ID the value for mutation.GENETIC_PROFILE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setGENETIC_PROFILE_ID(Integer GENETIC_PROFILE_ID) {
        this.GENETIC_PROFILE_ID = GENETIC_PROFILE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.SAMPLE_ID
     *
     * @return the value of mutation.SAMPLE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getSAMPLE_ID() {
        return SAMPLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.SAMPLE_ID
     *
     * @param SAMPLE_ID the value for mutation.SAMPLE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setSAMPLE_ID(Integer SAMPLE_ID) {
        this.SAMPLE_ID = SAMPLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.ENTREZ_GENE_ID
     *
     * @return the value of mutation.ENTREZ_GENE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getENTREZ_GENE_ID() {
        return ENTREZ_GENE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.ENTREZ_GENE_ID
     *
     * @param ENTREZ_GENE_ID the value for mutation.ENTREZ_GENE_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setENTREZ_GENE_ID(Integer ENTREZ_GENE_ID) {
        this.ENTREZ_GENE_ID = ENTREZ_GENE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.CENTER
     *
     * @return the value of mutation.CENTER
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getCENTER() {
        return CENTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.CENTER
     *
     * @param CENTER the value for mutation.CENTER
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setCENTER(String CENTER) {
        this.CENTER = CENTER == null ? null : CENTER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.SEQUENCER
     *
     * @return the value of mutation.SEQUENCER
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getSEQUENCER() {
        return SEQUENCER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.SEQUENCER
     *
     * @param SEQUENCER the value for mutation.SEQUENCER
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setSEQUENCER(String SEQUENCER) {
        this.SEQUENCER = SEQUENCER == null ? null : SEQUENCER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.MUTATION_STATUS
     *
     * @return the value of mutation.MUTATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getMUTATION_STATUS() {
        return MUTATION_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.MUTATION_STATUS
     *
     * @param MUTATION_STATUS the value for mutation.MUTATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setMUTATION_STATUS(String MUTATION_STATUS) {
        this.MUTATION_STATUS = MUTATION_STATUS == null ? null : MUTATION_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.VALIDATION_STATUS
     *
     * @return the value of mutation.VALIDATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getVALIDATION_STATUS() {
        return VALIDATION_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.VALIDATION_STATUS
     *
     * @param VALIDATION_STATUS the value for mutation.VALIDATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setVALIDATION_STATUS(String VALIDATION_STATUS) {
        this.VALIDATION_STATUS = VALIDATION_STATUS == null ? null : VALIDATION_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.TUMOR_SEQ_ALLELE1
     *
     * @return the value of mutation.TUMOR_SEQ_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getTUMOR_SEQ_ALLELE1() {
        return TUMOR_SEQ_ALLELE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.TUMOR_SEQ_ALLELE1
     *
     * @param TUMOR_SEQ_ALLELE1 the value for mutation.TUMOR_SEQ_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setTUMOR_SEQ_ALLELE1(String TUMOR_SEQ_ALLELE1) {
        this.TUMOR_SEQ_ALLELE1 = TUMOR_SEQ_ALLELE1 == null ? null : TUMOR_SEQ_ALLELE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.TUMOR_SEQ_ALLELE2
     *
     * @return the value of mutation.TUMOR_SEQ_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getTUMOR_SEQ_ALLELE2() {
        return TUMOR_SEQ_ALLELE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.TUMOR_SEQ_ALLELE2
     *
     * @param TUMOR_SEQ_ALLELE2 the value for mutation.TUMOR_SEQ_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setTUMOR_SEQ_ALLELE2(String TUMOR_SEQ_ALLELE2) {
        this.TUMOR_SEQ_ALLELE2 = TUMOR_SEQ_ALLELE2 == null ? null : TUMOR_SEQ_ALLELE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.MATCHED_NORM_SAMPLE_BARCODE
     *
     * @return the value of mutation.MATCHED_NORM_SAMPLE_BARCODE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getMATCHED_NORM_SAMPLE_BARCODE() {
        return MATCHED_NORM_SAMPLE_BARCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.MATCHED_NORM_SAMPLE_BARCODE
     *
     * @param MATCHED_NORM_SAMPLE_BARCODE the value for mutation.MATCHED_NORM_SAMPLE_BARCODE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setMATCHED_NORM_SAMPLE_BARCODE(String MATCHED_NORM_SAMPLE_BARCODE) {
        this.MATCHED_NORM_SAMPLE_BARCODE = MATCHED_NORM_SAMPLE_BARCODE == null ? null : MATCHED_NORM_SAMPLE_BARCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.MATCH_NORM_SEQ_ALLELE1
     *
     * @return the value of mutation.MATCH_NORM_SEQ_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getMATCH_NORM_SEQ_ALLELE1() {
        return MATCH_NORM_SEQ_ALLELE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.MATCH_NORM_SEQ_ALLELE1
     *
     * @param MATCH_NORM_SEQ_ALLELE1 the value for mutation.MATCH_NORM_SEQ_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setMATCH_NORM_SEQ_ALLELE1(String MATCH_NORM_SEQ_ALLELE1) {
        this.MATCH_NORM_SEQ_ALLELE1 = MATCH_NORM_SEQ_ALLELE1 == null ? null : MATCH_NORM_SEQ_ALLELE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.MATCH_NORM_SEQ_ALLELE2
     *
     * @return the value of mutation.MATCH_NORM_SEQ_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getMATCH_NORM_SEQ_ALLELE2() {
        return MATCH_NORM_SEQ_ALLELE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.MATCH_NORM_SEQ_ALLELE2
     *
     * @param MATCH_NORM_SEQ_ALLELE2 the value for mutation.MATCH_NORM_SEQ_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setMATCH_NORM_SEQ_ALLELE2(String MATCH_NORM_SEQ_ALLELE2) {
        this.MATCH_NORM_SEQ_ALLELE2 = MATCH_NORM_SEQ_ALLELE2 == null ? null : MATCH_NORM_SEQ_ALLELE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.TUMOR_VALIDATION_ALLELE1
     *
     * @return the value of mutation.TUMOR_VALIDATION_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getTUMOR_VALIDATION_ALLELE1() {
        return TUMOR_VALIDATION_ALLELE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.TUMOR_VALIDATION_ALLELE1
     *
     * @param TUMOR_VALIDATION_ALLELE1 the value for mutation.TUMOR_VALIDATION_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setTUMOR_VALIDATION_ALLELE1(String TUMOR_VALIDATION_ALLELE1) {
        this.TUMOR_VALIDATION_ALLELE1 = TUMOR_VALIDATION_ALLELE1 == null ? null : TUMOR_VALIDATION_ALLELE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.TUMOR_VALIDATION_ALLELE2
     *
     * @return the value of mutation.TUMOR_VALIDATION_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getTUMOR_VALIDATION_ALLELE2() {
        return TUMOR_VALIDATION_ALLELE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.TUMOR_VALIDATION_ALLELE2
     *
     * @param TUMOR_VALIDATION_ALLELE2 the value for mutation.TUMOR_VALIDATION_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setTUMOR_VALIDATION_ALLELE2(String TUMOR_VALIDATION_ALLELE2) {
        this.TUMOR_VALIDATION_ALLELE2 = TUMOR_VALIDATION_ALLELE2 == null ? null : TUMOR_VALIDATION_ALLELE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.MATCH_NORM_VALIDATION_ALLELE1
     *
     * @return the value of mutation.MATCH_NORM_VALIDATION_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getMATCH_NORM_VALIDATION_ALLELE1() {
        return MATCH_NORM_VALIDATION_ALLELE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.MATCH_NORM_VALIDATION_ALLELE1
     *
     * @param MATCH_NORM_VALIDATION_ALLELE1 the value for mutation.MATCH_NORM_VALIDATION_ALLELE1
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setMATCH_NORM_VALIDATION_ALLELE1(String MATCH_NORM_VALIDATION_ALLELE1) {
        this.MATCH_NORM_VALIDATION_ALLELE1 = MATCH_NORM_VALIDATION_ALLELE1 == null ? null : MATCH_NORM_VALIDATION_ALLELE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.MATCH_NORM_VALIDATION_ALLELE2
     *
     * @return the value of mutation.MATCH_NORM_VALIDATION_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getMATCH_NORM_VALIDATION_ALLELE2() {
        return MATCH_NORM_VALIDATION_ALLELE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.MATCH_NORM_VALIDATION_ALLELE2
     *
     * @param MATCH_NORM_VALIDATION_ALLELE2 the value for mutation.MATCH_NORM_VALIDATION_ALLELE2
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setMATCH_NORM_VALIDATION_ALLELE2(String MATCH_NORM_VALIDATION_ALLELE2) {
        this.MATCH_NORM_VALIDATION_ALLELE2 = MATCH_NORM_VALIDATION_ALLELE2 == null ? null : MATCH_NORM_VALIDATION_ALLELE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.VERIFICATION_STATUS
     *
     * @return the value of mutation.VERIFICATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getVERIFICATION_STATUS() {
        return VERIFICATION_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.VERIFICATION_STATUS
     *
     * @param VERIFICATION_STATUS the value for mutation.VERIFICATION_STATUS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setVERIFICATION_STATUS(String VERIFICATION_STATUS) {
        this.VERIFICATION_STATUS = VERIFICATION_STATUS == null ? null : VERIFICATION_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.SEQUENCING_PHASE
     *
     * @return the value of mutation.SEQUENCING_PHASE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getSEQUENCING_PHASE() {
        return SEQUENCING_PHASE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.SEQUENCING_PHASE
     *
     * @param SEQUENCING_PHASE the value for mutation.SEQUENCING_PHASE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setSEQUENCING_PHASE(String SEQUENCING_PHASE) {
        this.SEQUENCING_PHASE = SEQUENCING_PHASE == null ? null : SEQUENCING_PHASE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.SEQUENCE_SOURCE
     *
     * @return the value of mutation.SEQUENCE_SOURCE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getSEQUENCE_SOURCE() {
        return SEQUENCE_SOURCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.SEQUENCE_SOURCE
     *
     * @param SEQUENCE_SOURCE the value for mutation.SEQUENCE_SOURCE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setSEQUENCE_SOURCE(String SEQUENCE_SOURCE) {
        this.SEQUENCE_SOURCE = SEQUENCE_SOURCE == null ? null : SEQUENCE_SOURCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.VALIDATION_METHOD
     *
     * @return the value of mutation.VALIDATION_METHOD
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getVALIDATION_METHOD() {
        return VALIDATION_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.VALIDATION_METHOD
     *
     * @param VALIDATION_METHOD the value for mutation.VALIDATION_METHOD
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setVALIDATION_METHOD(String VALIDATION_METHOD) {
        this.VALIDATION_METHOD = VALIDATION_METHOD == null ? null : VALIDATION_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.SCORE
     *
     * @return the value of mutation.SCORE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getSCORE() {
        return SCORE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.SCORE
     *
     * @param SCORE the value for mutation.SCORE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setSCORE(String SCORE) {
        this.SCORE = SCORE == null ? null : SCORE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.BAM_FILE
     *
     * @return the value of mutation.BAM_FILE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getBAM_FILE() {
        return BAM_FILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.BAM_FILE
     *
     * @param BAM_FILE the value for mutation.BAM_FILE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setBAM_FILE(String BAM_FILE) {
        this.BAM_FILE = BAM_FILE == null ? null : BAM_FILE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.TUMOR_ALT_COUNT
     *
     * @return the value of mutation.TUMOR_ALT_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getTUMOR_ALT_COUNT() {
        return TUMOR_ALT_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.TUMOR_ALT_COUNT
     *
     * @param TUMOR_ALT_COUNT the value for mutation.TUMOR_ALT_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setTUMOR_ALT_COUNT(Integer TUMOR_ALT_COUNT) {
        this.TUMOR_ALT_COUNT = TUMOR_ALT_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.TUMOR_REF_COUNT
     *
     * @return the value of mutation.TUMOR_REF_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getTUMOR_REF_COUNT() {
        return TUMOR_REF_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.TUMOR_REF_COUNT
     *
     * @param TUMOR_REF_COUNT the value for mutation.TUMOR_REF_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setTUMOR_REF_COUNT(Integer TUMOR_REF_COUNT) {
        this.TUMOR_REF_COUNT = TUMOR_REF_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.NORMAL_ALT_COUNT
     *
     * @return the value of mutation.NORMAL_ALT_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getNORMAL_ALT_COUNT() {
        return NORMAL_ALT_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.NORMAL_ALT_COUNT
     *
     * @param NORMAL_ALT_COUNT the value for mutation.NORMAL_ALT_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setNORMAL_ALT_COUNT(Integer NORMAL_ALT_COUNT) {
        this.NORMAL_ALT_COUNT = NORMAL_ALT_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mutation.NORMAL_REF_COUNT
     *
     * @return the value of mutation.NORMAL_REF_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Integer getNORMAL_REF_COUNT() {
        return NORMAL_REF_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mutation.NORMAL_REF_COUNT
     *
     * @param NORMAL_REF_COUNT the value for mutation.NORMAL_REF_COUNT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setNORMAL_REF_COUNT(Integer NORMAL_REF_COUNT) {
        this.NORMAL_REF_COUNT = NORMAL_REF_COUNT;
    }
}