package org.mskcc.cbio.clinicaldata.cbiodata.model;

public class CbioTypeOfCancer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_of_cancer.TYPE_OF_CANCER_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String TYPE_OF_CANCER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_of_cancer.NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_of_cancer.CLINICAL_TRIAL_KEYWORDS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String CLINICAL_TRIAL_KEYWORDS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_of_cancer.DEDICATED_COLOR
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String DEDICATED_COLOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_of_cancer.SHORT_NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String SHORT_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_of_cancer.PARENT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String PARENT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_of_cancer.TYPE_OF_CANCER_ID
     *
     * @return the value of type_of_cancer.TYPE_OF_CANCER_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getTYPE_OF_CANCER_ID() {
        return TYPE_OF_CANCER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_of_cancer.TYPE_OF_CANCER_ID
     *
     * @param TYPE_OF_CANCER_ID the value for type_of_cancer.TYPE_OF_CANCER_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setTYPE_OF_CANCER_ID(String TYPE_OF_CANCER_ID) {
        this.TYPE_OF_CANCER_ID = TYPE_OF_CANCER_ID == null ? null : TYPE_OF_CANCER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_of_cancer.NAME
     *
     * @return the value of type_of_cancer.NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_of_cancer.NAME
     *
     * @param NAME the value for type_of_cancer.NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_of_cancer.CLINICAL_TRIAL_KEYWORDS
     *
     * @return the value of type_of_cancer.CLINICAL_TRIAL_KEYWORDS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getCLINICAL_TRIAL_KEYWORDS() {
        return CLINICAL_TRIAL_KEYWORDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_of_cancer.CLINICAL_TRIAL_KEYWORDS
     *
     * @param CLINICAL_TRIAL_KEYWORDS the value for type_of_cancer.CLINICAL_TRIAL_KEYWORDS
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setCLINICAL_TRIAL_KEYWORDS(String CLINICAL_TRIAL_KEYWORDS) {
        this.CLINICAL_TRIAL_KEYWORDS = CLINICAL_TRIAL_KEYWORDS == null ? null : CLINICAL_TRIAL_KEYWORDS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_of_cancer.DEDICATED_COLOR
     *
     * @return the value of type_of_cancer.DEDICATED_COLOR
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getDEDICATED_COLOR() {
        return DEDICATED_COLOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_of_cancer.DEDICATED_COLOR
     *
     * @param DEDICATED_COLOR the value for type_of_cancer.DEDICATED_COLOR
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setDEDICATED_COLOR(String DEDICATED_COLOR) {
        this.DEDICATED_COLOR = DEDICATED_COLOR == null ? null : DEDICATED_COLOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_of_cancer.SHORT_NAME
     *
     * @return the value of type_of_cancer.SHORT_NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getSHORT_NAME() {
        return SHORT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_of_cancer.SHORT_NAME
     *
     * @param SHORT_NAME the value for type_of_cancer.SHORT_NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setSHORT_NAME(String SHORT_NAME) {
        this.SHORT_NAME = SHORT_NAME == null ? null : SHORT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_of_cancer.PARENT
     *
     * @return the value of type_of_cancer.PARENT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getPARENT() {
        return PARENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_of_cancer.PARENT
     *
     * @param PARENT the value for type_of_cancer.PARENT
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setPARENT(String PARENT) {
        this.PARENT = PARENT == null ? null : PARENT.trim();
    }
}