package org.mskcc.cbio.clinicaldata.cbiodata.model;

public class CbioClinicalAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_attribute.ATTR_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String ATTR_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_attribute.DISPLAY_NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String DISPLAY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_attribute.DESCRIPTION
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String DESCRIPTION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_attribute.DATATYPE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String DATATYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_attribute.PATIENT_ATTRIBUTE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private Boolean PATIENT_ATTRIBUTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_attribute.PRIORITY
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String PRIORITY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_attribute.ATTR_ID
     *
     * @return the value of clinical_attribute.ATTR_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getATTR_ID() {
        return ATTR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_attribute.ATTR_ID
     *
     * @param ATTR_ID the value for clinical_attribute.ATTR_ID
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setATTR_ID(String ATTR_ID) {
        this.ATTR_ID = ATTR_ID == null ? null : ATTR_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_attribute.DISPLAY_NAME
     *
     * @return the value of clinical_attribute.DISPLAY_NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getDISPLAY_NAME() {
        return DISPLAY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_attribute.DISPLAY_NAME
     *
     * @param DISPLAY_NAME the value for clinical_attribute.DISPLAY_NAME
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setDISPLAY_NAME(String DISPLAY_NAME) {
        this.DISPLAY_NAME = DISPLAY_NAME == null ? null : DISPLAY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_attribute.DESCRIPTION
     *
     * @return the value of clinical_attribute.DESCRIPTION
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_attribute.DESCRIPTION
     *
     * @param DESCRIPTION the value for clinical_attribute.DESCRIPTION
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_attribute.DATATYPE
     *
     * @return the value of clinical_attribute.DATATYPE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getDATATYPE() {
        return DATATYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_attribute.DATATYPE
     *
     * @param DATATYPE the value for clinical_attribute.DATATYPE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setDATATYPE(String DATATYPE) {
        this.DATATYPE = DATATYPE == null ? null : DATATYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_attribute.PATIENT_ATTRIBUTE
     *
     * @return the value of clinical_attribute.PATIENT_ATTRIBUTE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public Boolean getPATIENT_ATTRIBUTE() {
        return PATIENT_ATTRIBUTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_attribute.PATIENT_ATTRIBUTE
     *
     * @param PATIENT_ATTRIBUTE the value for clinical_attribute.PATIENT_ATTRIBUTE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setPATIENT_ATTRIBUTE(Boolean PATIENT_ATTRIBUTE) {
        this.PATIENT_ATTRIBUTE = PATIENT_ATTRIBUTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_attribute.PRIORITY
     *
     * @return the value of clinical_attribute.PRIORITY
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getPRIORITY() {
        return PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_attribute.PRIORITY
     *
     * @param PRIORITY the value for clinical_attribute.PRIORITY
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setPRIORITY(String PRIORITY) {
        this.PRIORITY = PRIORITY == null ? null : PRIORITY.trim();
    }
}