package org.mskcc.cbio.clinicaldata.cbiodata.model;

public class CbioClinicalPatient extends CbioClinicalPatientKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clinical_patient.ATTR_VALUE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    private String ATTR_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clinical_patient.ATTR_VALUE
     *
     * @return the value of clinical_patient.ATTR_VALUE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public String getATTR_VALUE() {
        return ATTR_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clinical_patient.ATTR_VALUE
     *
     * @param ATTR_VALUE the value for clinical_patient.ATTR_VALUE
     *
     * @mbggenerated Mon Apr 20 14:27:25 EDT 2015
     */
    public void setATTR_VALUE(String ATTR_VALUE) {
        this.ATTR_VALUE = ATTR_VALUE == null ? null : ATTR_VALUE.trim();
    }
}